(function(){
'use strict';const P=TimePhysics,$=s=>document.querySelector(s);let history=[],cursor=0,n=40,timer=0,direction=1;
const left=s=>s.reduce((a,b)=>a+b,0);
function canvas(el){const r=el.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);el.width=Math.round(r.width*dpr);el.height=Math.round(r.height*dpr);const ctx=el.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return {ctx,w:r.width,h:r.height};}
function stop(){clearInterval(timer);timer=0;$('#play').textContent='Démarrer les transitions';$('#play').setAttribute('aria-pressed','false');$('#reverse').textContent='Rejouer à rebours';$('#reverse').setAttribute('aria-pressed','false');}
function draw(){const k=left(history[cursor]),entropy=P.logMultiplicity(n,k),maxEntropy=P.logMultiplicity(n,Math.floor(n/2));$('#left-count').textContent=`${k} / ${n}`;$('#entropy').textContent=entropy.toLocaleString('fr-FR',{maximumFractionDigits:2});$('#multiplicity').textContent=entropy===0?'1':Math.exp(entropy).toLocaleString('fr-FR',entropy>14?{notation:'scientific',maximumFractionDigits:2}:{maximumFractionDigits:0});$('#left-dots').innerHTML='<i></i>'.repeat(k);$('#right-dots').innerHTML='<i></i>'.repeat(n-k);$('#urn-scene').setAttribute('aria-label',`${k} objets à gauche, ${n-k} à droite.`);$('#history').max=history.length-1;$('#history').value=cursor;$('#history').disabled=history.length===1;$('#history-value').textContent=`${cursor} / ${history.length-1}`;$('#reverse').disabled=cursor===0;
const {ctx,w,h}=canvas($('#entropy-chart'));ctx.fillStyle='#0b0e0b';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#33422d';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(0,15);ctx.lineTo(w,15);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#c5b4ef';ctx.lineWidth=1.7;ctx.beginPath();history.forEach((state,i)=>{const x=10+i/Math.max(1,history.length-1)*(w-20),y=h-15-P.logMultiplicity(n,left(state))/maxEntropy*(h-30);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();ctx.fillStyle='#eac69a';ctx.beginPath();ctx.arc(10+cursor/Math.max(1,history.length-1)*(w-20),h-15-entropy/maxEntropy*(h-30),4,0,Math.PI*2);ctx.fill();$('#entropy-chart').setAttribute('aria-label',`Transition ${cursor} sur ${history.length-1}. Entropie ${entropy.toFixed(2)} en unités de k_B. Maximum de comptage ${maxEntropy.toFixed(2)}.`);
const chart=canvas($('#equilibrium-chart')),p=P.equilibrium(n),peak=Math.max(...p);chart.ctx.fillStyle='#0b0e0b';chart.ctx.fillRect(0,0,chart.w,chart.h);p.forEach((v,i)=>{chart.ctx.fillStyle=i===k?'#eac69a':'#c5b4ef77';const x=i*chart.w/(n+1),height=v/peak*(chart.h-28);chart.ctx.fillRect(x,chart.h-14-height,Math.max(1,chart.w/(n+1)-1),height);});chart.ctx.strokeStyle='#eac69a';chart.ctx.beginPath();const x=(k+.5)*chart.w/(n+1);chart.ctx.moveTo(x,5);chart.ctx.lineTo(x,chart.h-5);chart.ctx.stroke();}
function forward(){if(cursor<history.length-1)cursor++;else if(history.length<=1000){history.push(P.step(history.at(-1)));cursor++;}else{stop();$('#status').textContent='1 000 transitions enregistrées. Parcourez l’histoire ou recommencez.';}}
function advance(count){for(let i=0;i<count;i++)forward();draw();if(history.length<=1000)$('#status').textContent=`Transition ${cursor}. Le macroétat peut évoluer vers plus ou moins de configurations.`;}
function reset(){stop();n=Number($('#object-count').value);history=[Array.from({length:n},(_,i)=>$('#initial').value==='left'||i<n/2?1:0)];cursor=0;draw();$('#status').textContent='Nouvelle histoire. Les compteurs et les transitions ont été réinitialisés.';}
$('#play').addEventListener('click',()=>{if(timer&&direction===1){stop();$('#status').textContent='En pause.';return;}stop();direction=1;$('#play').textContent='Mettre en pause';$('#play').setAttribute('aria-pressed','true');timer=setInterval(()=>advance(2),120);});$('#reverse').addEventListener('click',()=>{if(timer&&direction===-1){stop();return;}stop();direction=-1;$('#reverse').textContent='Arrêter la relecture';$('#reverse').setAttribute('aria-pressed','true');$('#status').textContent='Relecture exacte des états enregistrés, du présent vers le départ.';timer=setInterval(()=>{cursor=Math.max(0,cursor-1);draw();if(cursor===0){stop();$('#status').textContent='Retour au premier état enregistré. Aucune dynamique physique n’a été inversée.';}},70);});$('#step').addEventListener('click',()=>{stop();advance(1);});$('#batch').addEventListener('click',()=>{stop();advance(50);});$('#history').addEventListener('input',()=>{stop();cursor=Number($('#history').value);draw();$('#status').textContent=`État enregistré ${cursor}. Vous parcourez une histoire existante.`;});$('#reset').addEventListener('click',reset);$('#object-count').addEventListener('change',reset);$('#initial').addEventListener('change',reset);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});addEventListener('resize',draw);reset();
})();
