const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const C=require('../atlas/core.js'),M=require('../atlas/metadata.js'),Consent=require('../atlas/consent.js');
const data={questions:[{id:29,title:'Matière noire',status:'À explorer',researched:false},{id:33,title:'Origine de la vie',status:'Synthèse provisoire',researched:true,learning:{goal:'Explorer les étapes de l’abiogenèse.'}}],paths:[]};
function document(){const tags=new Map(),doc={title:'',head:{append(el){tags.set(Symbol(),el);}},querySelector(selector){return tags.get(selector)||[...tags.values()].find(el=>el.selector===selector)||null;},createElement(){return {setAttribute(key,value){this[key]=value;if(key==='name'||key==='property')this.selector=`meta[${key}="${value}"]`;}};}};tags.set('link[rel="canonical"]',{href:'https://the42laws.fr/dossiers/29/'});return doc;}
test('metadata refreshes robots, descriptions and social tags through 29 → 33 → back → home',()=>{const doc=document();for(const id of [29,33,29,33]){const meta=M.pageMetadata(data,['question',String(id)]);M.applyMetadata(doc,meta);assert.equal(doc.querySelector('meta[name="robots"]').content,id===29?'noindex,follow':'index,follow');assert.equal(doc.querySelector('meta[name="description"]').content,meta.description);assert.equal(doc.querySelector('meta[property="og:description"]').content,meta.description);assert.equal(doc.querySelector('link[rel="canonical"]').href,`https://the42laws.fr${C.questionPath(id)}`);assert.ok(M.headMarkup(meta,'https://the42laws.fr/').includes(`content="${meta.robots}"`));}M.applyMetadata(doc,M.pageMetadata(data,['accueil']));assert.equal(doc.querySelector('meta[name="robots"]').content,'index,follow');assert.equal(doc.querySelector('link[rel="canonical"]').href,'https://the42laws.fr/');});
test('direct legal URLs and legacy dossier navigation resolve coherently',()=>{assert.deepEqual(C.locationRoute('/confidentialite/','','').parts,['confidentialite']);assert.equal(M.pageMetadata(data,['carnet']).robots,'noindex,follow');assert.equal(M.pageMetadata(data,['question','999']).robots,'noindex,follow');assert.equal(C.canonicalHref('#/question/33?lecture=sources'),C.questionPath(33)+'?lecture=sources');});
const experience={laboratory:'trou-noir',guide:'horizon',modelVersion:1,title:'Deux masses',question:21,prediction:'Le rayon double',explanation:'rₛ est proportionnel à M',settings:{mass:20,zoom:1},captures:{A:{time:'2026-09-30T10:00:00Z',settings:{mass:10},results:{rayon:'29,53 km'}},B:{settings:{mass:20},results:{rayon:'59,07 km'}}},limit:'Sans rotation',updatedAt:'2026-09-30T10:01:00Z'};
const exportState=state=>JSON.stringify({application:'The42laws',...state});
test('old notebooks migrate without changing personal data; new experiences round-trip',()=>{const old={version:1,read:[33],saved:[29],notes:{33:'Note préservée'},labs:['neutrino'],last:33};const migrated=C.parseNotebookJSON(exportState(old));assert.equal(migrated.version,2);assert.deepEqual(migrated.experiences,{});const current=C.cleanState({...migrated,experiences:{'trou-noir:horizon':experience}});assert.deepEqual(C.parseNotebookJSON(exportState(current)),current);assert.equal(current.notes[33],'Note préservée');});
test('imports protect existing experience by default and replace only when selected',()=>{const a=C.cleanState({experiences:{'trou-noir:horizon':experience}}),b=C.cleanState({experiences:{'trou-noir:horizon':{...experience,prediction:'Autre prédiction'}}});assert.equal(C.mergeNotebook(a,b).experiences['trou-noir:horizon'].prediction,experience.prediction);assert.equal(C.mergeNotebook(a,b,true).experiences['trou-noir:horizon'].prediction,'Autre prédiction');assert.throws(()=>C.parseNotebookJSON(exportState({...a,experiences:{'trou-noir:horizon':{...experience,settings:{mass:[]}}}})),/invalide/);assert.throws(()=>C.parseNotebookJSON(exportState({...a,experiences:{'autre:horizon':experience}})),/invalide/);});
test('legacy standalone guide exports can be imported into the notebook',()=>{const {modelVersion,settings,...old}=experience;const incoming=C.parseNotebookJSON(JSON.stringify({application:'The42laws',...old}));assert.equal(incoming.experiences['trou-noir:horizon'].settings.mass,20);assert.equal(incoming.experiences['trou-noir:horizon'].captures.A.results.rayon,'29,53 km');});
test('lab saves read fresh storage, preserving another lab and question notes',()=>{let raw=exportState(C.cleanState({notes:{33:'Préserver'},experiences:{'trou-noir:horizon':experience}}));const context={AtlasCore:C,localStorage:{getItem:()=>raw,setItem:(key,value)=>raw=value}};vm.runInNewContext(fs.readFileSync('atlas/notebook.js','utf8'),context);context.AtlasNotebook.update(state=>({...state,experiences:{...state.experiences,'neutrino:oscillations':{...experience,laboratory:'neutrino',guide:'oscillations'}}}));assert.equal(JSON.parse(raw).notes[33],'Préserver');assert.equal(Object.keys(JSON.parse(raw).experiences).length,2);});
test('expired or malformed consent is not treated as acceptance and private text is excluded',()=>{const now=Date.now();assert.ok(Consent.validChoice({version:1,analytics:true,updatedAt:now},now));for(const v of [null,{version:1,analytics:'yes',updatedAt:now},{version:1,analytics:true,updatedAt:now+1},{version:1,analytics:true,updatedAt:now-181*86400000}])assert.equal(Consent.validChoice(v,now),false);assert.equal(Consent.safePage(new URL('https://the42laws.fr/#/carnet')),null);assert.equal(Consent.safePage(new URL('https://the42laws.fr/#/atlas?q=secret')), 'https://the42laws.fr/#/atlas');assert.equal(Consent.safePage(new URL('https://the42laws.fr/dossiers/33/?lecture=sources')), 'https://the42laws.fr'+C.questionPath(33));});
function consentBrowser(stored=null){const events={},clicks={},tags=[],writes=[];const elements={'.consent-status':{textContent:''},'[data-consent="yes"]':{hidden:false,addEventListener:(name,fn)=>clicks.yes=fn},'[data-consent="no"]':{textContent:'',addEventListener:(name,fn)=>clicks.no=fn}};let reloaded=0;const preference={addEventListener:(name,fn)=>clicks.preferences=fn};const banner={hidden:false,focus(){},setAttribute(){},querySelector:s=>elements[s]||{focus(){}}};const doc={title:'Titre public',cookie:'_ga=old',head:{append:el=>tags.push(el)},body:{append(){}},querySelector:()=>({dataset:{measurementId:'G-L659XPNBR6'}}),querySelectorAll:()=>[preference],createElement:kind=>kind==='section'?banner:{},addEventListener:(name,fn)=>clicks[name]=fn};const context={document:doc,location:{origin:'https://the42laws.fr',pathname:'/',hash:'#/accueil',hostname:'the42laws.fr',reload(){reloaded++;}},localStorage:{getItem:()=>stored,setItem:(k,v)=>{stored=v;writes.push(v);}},addEventListener:(name,fn)=>events[name]=fn,Date,Number,JSON,URL};vm.runInNewContext(fs.readFileSync('atlas/consent.js','utf8'),context);return {context,tags,writes,banner,events,choose(value){clicks[value]();},open(){clicks.preferences();},setStored(value){stored=JSON.stringify(value);},reloads:()=>reloaded};}
test('consent blocks all Google scripts before choice and after refusal; acceptance loads once',()=>{const s=consentBrowser();assert.equal(s.tags.length,0);s.choose('no');assert.equal(s.tags.length,0);s.open();assert.equal(s.banner.hidden,false);assert.equal(JSON.parse(s.writes[0]).analytics,false);s.choose('yes');assert.equal(s.tags.length,1);assert.equal(s.tags[0].src,'https://www.googletagmanager.com/gtag/js?id=G-L659XPNBR6');s.events['the42laws:route']();assert.equal(s.tags.length,1);const queue=s.context.dataLayer.map(args=>Array.from(args));assert.ok(queue.find(args=>args[0]==='consent'&&args[1]==='default'&&args[2].analytics_storage==='denied'));assert.ok(queue.find(args=>args[0]==='consent'&&args[1]==='update'&&args[2].ad_user_data==='denied'));assert.equal(queue.filter(args=>args[1]==='page_view').length,1);s.context.location.hash='#/atlas?q=texte-prive';s.events['the42laws:route']();assert.ok(!JSON.stringify(s.context.dataLayer).includes('texte-prive'));s.context.location.hash='#/carnet';s.events['the42laws:route']();assert.ok(!JSON.stringify(s.context.dataLayer).includes('#/carnet'));s.choose('no');assert.equal(s.context['ga-disable-G-L659XPNBR6'],true);assert.equal(s.reloads(),1);});
test('remembered refusal, expired acceptance and private-only visit never load Google',()=>{for(const choice of [{version:1,analytics:false,updatedAt:Date.now()},{version:1,analytics:true,updatedAt:Date.now()-181*86400000}])assert.equal(consentBrowser(JSON.stringify(choice)).tags.length,0);const s=consentBrowser();s.context.location.hash='#/carnet';s.choose('yes');assert.equal(s.tags.length,0);s.context.location.hash='#/atlas';s.events['the42laws:route']();assert.equal(s.tags.length,1);});

test('browser back cache rechecks withdrawal before emitting another page view',()=>{const s=consentBrowser();s.choose('yes');const before=s.context.dataLayer.length;s.setStored({version:1,analytics:false,updatedAt:Date.now()});s.events['the42laws:route']();assert.equal(s.context.dataLayer.length,before);assert.equal(s.context['ga-disable-G-L659XPNBR6'],true);assert.equal(s.reloads(),1);});
