const test=require('node:test'),assert=require('node:assert/strict');
const P=require('../photon/physics.js'),T=require('../temps/physics.js'),C=require('../atlas/core.js');
const p={wavelength:550e-9,distance:2,separation:180e-6,width:30e-6,slits:2,whichPath:false};
const near=(a,b,t=1e-10)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
test('double slit has a central maximum, a dark half-fringe and even symmetry',()=>{near(P.intensity(0,p),2);const fringe=p.wavelength*p.distance/p.separation;near(P.intensity(fringe/2,p),0);for(let i=0;i<50;i++)near(P.intensity(i*.0004,p),P.intensity(-i*.0004,p));});
test('distinguishable paths retain the single slit envelope without fringes',()=>{const marked={...p,whichPath:true},single={...p,slits:1};for(let i=-50;i<=50;i++)near(P.intensity(i*.0003,marked),P.intensity(i*.0003,single));const diffractionZero=p.wavelength*p.distance/p.width;near(P.intensity(diffractionZero,single),0);assert.ok(P.intensity(p.wavelength*p.distance/p.separation/2,marked)>0);});
test('all available wavelength and separation extrema give normalized probabilities',()=>{for(const wavelength of [380e-9,780e-9])for(const separation of [80e-6,300e-6])for(const whichPath of [false,true]){const d=P.distribution({...p,wavelength,separation,whichPath});near(d.probabilities.reduce((a,b)=>a+b),1);assert.ok(d.probabilities.every(x=>x>=0&&Number.isFinite(x)));assert.ok(d.cdf.every((v,i)=>i===0||v>=d.cdf[i-1]));assert.ok(Math.abs(P.sample(d,()=>.5))<.0001);}});
test('photon energy uses SI constants and invalid input is rejected',()=>{near(P.energyEV(500e-9),2.479683968664005,1e-12);for(const wavelength of [0,-1,NaN])assert.throws(()=>P.energyEV(wavelength));assert.throws(()=>P.intensity(0,{...p,width:p.separation}));assert.throws(()=>P.distribution(p,0));assert.throws(()=>P.sample(P.distribution(p),()=>1));});
test('urn multiplicities match independent enumeration and preserve symmetry',()=>{const counts=new Array(9).fill(0);for(let mask=0;mask<256;mask++)counts[mask.toString(2).replaceAll('0','').length]++;for(let k=0;k<=8;k++){near(Math.exp(T.logMultiplicity(8,k)),counts[k],1e-9);near(T.logMultiplicity(8,k),T.logMultiplicity(8,8-k));}near(T.logMultiplicity(40,0),0);assert.ok(T.logMultiplicity(40,20)>T.logMultiplicity(40,1));});
test('urn equilibrium is normalized and satisfies detailed balance',()=>{for(const n of [20,40,80]){const pi=T.equilibrium(n);near(pi.reduce((a,b)=>a+b),1);for(let k=0;k<n;k++)near(pi[k]*(n-k)/(2*n),pi[k+1]*(k+1)/(2*n));}});
test('urn transition can stay or flip exactly one bit without mutating history',()=>{const original=[1,1,0,0];let seq=[.25,.1];assert.deepEqual(T.step(original,()=>seq.shift()),[1,0,0,0]);assert.deepEqual(original,[1,1,0,0]);seq=[.25,.9];assert.deepEqual(T.step(original,()=>seq.shift()),original);assert.throws(()=>T.step([2]));assert.throws(()=>T.logMultiplicity(5,6));});
function notebook(overrides={}){return {application:'The42laws',version:1,read:[15],saved:[10],notes:{15:'Imported'},labs:['photon'],last:15,...overrides};}
test('imports validate exports, reject hostile or unsupported structures',()=>{const parsed=C.parseNotebookJSON(JSON.stringify(notebook()));assert.equal(parsed.notes[15],'Imported');assert.deepEqual(parsed.labs,['photon']);for(const invalid of ['{}','no JSON',JSON.stringify(notebook({version:9})),JSON.stringify(notebook({read:[99]})),JSON.stringify(notebook({notes:{15:'x'.repeat(50001)}})),JSON.stringify(notebook({notes:[]})),JSON.stringify(notebook({notes:{'__proto__':'bad',constructor:'bad'}})),JSON.stringify(notebook({labs:['unknown']}))])assert.throws(()=>C.parseNotebookJSON(invalid));});
test('default import merge preserves existing conflicts and unites progression',()=>{const existing={read:[41],saved:[23],notes:{15:'Current',41:'Keep me'},labs:['neutrino'],last:41};const imported=notebook({notes:{15:'Imported',10:'New'}}),merged=C.mergeNotebook(existing,imported);assert.equal(merged.notes[15],'Current');assert.equal(merged.notes[41],'Keep me');assert.equal(merged.notes[10],'New');assert.deepEqual(merged.read,[41,15]);assert.deepEqual(merged.saved,[23,10]);assert.equal(C.mergeNotebook(existing,imported,true).notes[15],'Imported');assert.equal(existing.notes[15],'Current');});
