(function(){
'use strict';
const P=PhotonPhysics,$=s=>document.querySelector(s),screen=$('#screen'),hist=$('#histogram');let slits=2,points=[],running=false,frame=0,last=0,dist;
const params=()=>({wavelength:Number($('#wavelength').value)*1e-9,distance:2,separation:Number($('#separation').value)*1e-6,width:30e-6,slits,whichPath:slits===2&&$('#which-path').checked});
function canvas(c){const r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr);const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return {ctx,w:r.width,h:r.height};}
function draw(){const {ctx,w,h}=canvas(screen);ctx.fillStyle='#0b0e0b';ctx.fillRect(0,0,w,h);ctx.fillStyle='#b5dcfbaa';for(const pt of points){ctx.beginPath();ctx.arc((pt.x/dist.extent+1)*w/2,pt.y*(h-12)+6,1.35,0,Math.PI*2);ctx.fill();}const chart=canvas(hist),c=chart.ctx,W=chart.w,H=chart.h,nb=70,bins=new Array(nb).fill(0),theory=new Array(nb).fill(0);points.forEach(pt=>bins[Math.min(nb-1,Math.floor((pt.x/dist.extent+1)*nb/2))]++);dist.xs.forEach((x,i)=>theory[Math.min(nb-1,Math.floor((x/dist.extent+1)*nb/2))]+=dist.probabilities[i]);const values=bins.map(x=>points.length?x/points.length:0),max=Math.max(...values,...theory)*1.12;c.fillStyle='#0b0e0b';c.fillRect(0,0,W,H);c.fillStyle='#9cc7e766';values.forEach((v,i)=>c.fillRect(i*W/nb,H-15-(H-30)*v/max,Math.max(1,W/nb-1),(H-30)*v/max));if($('#show-theory').checked){c.strokeStyle='#c4f58b';c.lineWidth=1.6;c.beginPath();theory.forEach((v,i)=>{const x=(i+.5)*W/nb,y=H-15-(H-30)*v/max;i?c.lineTo(x,y):c.moveTo(x,y);});c.stroke();}$('#count').textContent=points.length.toLocaleString('fr-FR');screen.setAttribute('aria-label',`${points.length} impacts simulés sur un écran de −30 à +30 mm. ${slits===1?'Diffraction par une fente.':params().whichPath?'Deux chemins distinguables, sans franges.':'Deux chemins cohérents, franges d’interférence.'}`);}
function add(n){for(let i=0;i<n&&points.length<10000;i++)points.push({x:P.sample(dist),y:Math.random()});draw();if(points.length>=10000){stop();$('#status').textContent='10 000 impacts atteints. Effacez pour recommencer.';}}
function stop(){running=false;cancelAnimationFrame(frame);$('#play').textContent='Démarrer les impacts';$('#play').setAttribute('aria-pressed','false');}
function tick(now){if(!running)return;if(now-last>60){add(3);last=now;}if(running)frame=requestAnimationFrame(tick);}
function reset(message='Écran effacé. La distribution correspond aux réglages actuels.'){stop();points=[];dist=P.distribution(params());const p=params();$('#wavelength-value').textContent=`${$('#wavelength').value} nm`;$('#separation-value').textContent=`${$('#separation').value} µm`;$('#energy').textContent=P.energyEV(p.wavelength).toLocaleString('fr-FR',{maximumFractionDigits:2})+' eV';$('#fringe').textContent=slits===2&&!p.whichPath?(p.wavelength*p.distance/p.separation*1000).toLocaleString('fr-FR',{maximumFractionDigits:2})+' mm':'Sans franges';$('#which-path').disabled=slits===1;$('#separation').disabled=slits===1;$('#slit-label').innerHTML=slits===1?'Une fente<br><b>▏</b>':'Deux fentes<br><b>▏▏</b>';$('#path-help').textContent=slits===1?'Une ouverture : une enveloppe de diffraction, sans interférence entre deux fentes.':p.whichPath?'Chemins distinguables : le modèle additionne les probabilités. La conscience d’un observateur n’intervient pas.':'Deux chemins cohérents : les amplitudes interfèrent. Le dispositif ne distingue pas la fente empruntée.';$('#status').textContent=message;draw();}
document.querySelectorAll('[data-slits]').forEach(b=>b.addEventListener('click',()=>{slits=Number(b.dataset.slits);document.querySelectorAll('[data-slits]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));reset('Configuration modifiée : les impacts précédents ont été effacés.');}));
for(const id of ['wavelength','separation'])$('#'+id).addEventListener('input',()=>reset('Réglage modifié : les impacts précédents ont été effacés.'));
$('#which-path').addEventListener('change',()=>reset('Information de chemin modifiée : nouvel écran.'));$('#show-theory').addEventListener('change',draw);$('#reset').addEventListener('click',()=>reset());$('#one').addEventListener('click',()=>{add(1);if(points.length<10000)$('#status').textContent=`${points.length} impacts. Chaque position est tirée suivant la distribution du modèle.`;});$('#hundred').addEventListener('click',()=>{add(100);if(points.length<10000)$('#status').textContent=`${points.length} impacts accumulés.`;});$('#play').addEventListener('click',()=>{if(running){stop();$('#status').textContent='En pause. Les impacts restent visibles.';}else if(points.length<10000){running=true;$('#play').textContent='Mettre en pause';$('#play').setAttribute('aria-pressed','true');$('#status').textContent='Accumulation en cours. Vous pouvez mettre en pause à tout moment.';frame=requestAnimationFrame(tick);}});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});addEventListener('resize',draw);reset('Prêt. Ajoutez un impact ou lancez l’accumulation.');
})();
