import {readFile,writeFile} from 'node:fs/promises';
import {resolve,dirname,relative,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {Marked} from 'marked';
export const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function resolveLink(href,source){
 if(/^(https?:|mailto:)/i.test(href))return href;
 if(href.startsWith('#'))return href;
 if(/^[\w+.-]+:/.test(href)||href.startsWith('//')||/[\u0000-\u0020]/.test(href))return '#';
 const target=resolve(dirname(resolve(root,source)),href.split('#')[0]);
 const local=relative(root,target).split(sep).join('/');
 if(local.startsWith('../'))return '#';
 if(/^questions\/\d{2}\.md$/.test(local))return '#/question/'+Number(local.match(/\d{2}/)[0]);
 if(local==='QUESTIONS.md')return '#/atlas';
 if(local==='METHODE.md')return '#/methode';
 if(local==='sources/README.md')return '#/sources';
 return local+(href.includes('#')?'#'+href.split('#')[1]:'');
}
export function renderMarkdown(md,source='questions/41.md'){
 const headings=[];let n=0;
 const marked=new Marked({gfm:true,renderer:{
  html({text}){return esc(text);},
  image({text}){return esc(text);},
  heading({tokens,depth}){const title=this.parser.parseInline(tokens);const id='part-'+(++n);headings.push({id,title:title.replace(/<[^>]+>/g,''),depth});return `<h${Math.max(2,depth)} id="${id}" tabindex="-1">${title}</h${Math.max(2,depth)}>`;},
  link({href,title,tokens}){const url=resolveLink(href,source),external=/^https?:/i.test(url);return `<a href="${esc(url)}"${external?' target="_blank" rel="noopener noreferrer"':''}${title?` title="${esc(title)}"`:''}>${this.parser.parseInline(tokens)}</a>`;},
  table(token){const head=token.header.map(c=>`<th scope="col">${this.parser.parseInline(c.tokens)}</th>`).join('');const rows=token.rows.map(row=>`<tr>${row.map(c=>`<td>${this.parser.parseInline(c.tokens)}</td>`).join('')}</tr>`).join('');return `<div class="table-scroll" tabindex="0" role="region" aria-label="Tableau de recherche"><table><thead><tr>${head}</tr></thead><tbody>${rows}</tbody></table></div>`;}
 }});
 return {html:marked.parse(md),headings};
}
export async function build(){
 const metadata=JSON.parse(await readFile(resolve(root,'content/atlas.json'),'utf8'));
 const questions=[];
 for(let id=1;id<=42;id++){
  const file=`questions/${String(id).padStart(2,'0')}.md`,md=await readFile(resolve(root,file),'utf8');
  const title=md.match(/^# \d+\. (.+)$/m)?.[1],status=md.match(/^Statut de recherche : (.+)$/m)?.[1];
  if(!title||!status)throw Error(`Missing question metadata: ${file}`);
  const domain=metadata.domains.find(d=>id>=d.range[0]&&id<=d.range[1]);
  const researched=status!=='À explorer';
  const body=md.slice(md.indexOf('\n## ')+1);
  const match=body.match(/## Sources vérifiées\n([\s\S]*?)(?=\n## |$)/);
  const sources=match?match[1].trim():'';
  const sourceIds=[...new Set([...sources.matchAll(/\| (S\d{3}) \|/g)].map(m=>m[1]))];
  const document=renderMarkdown(body,file);
  const short=id===41?renderMarkdown(await readFile(resolve(root,'content/41-essentiel.md'),'utf8'),'content/41-essentiel.md'):null;
  questions.push({id,title,status,researched,domain:domain.id,domainName:domain.name,color:domain.color,file,updated:md.match(/^Dernière mise à jour : (.+)$/m)?.[1]||'',html:document.html,headings:document.headings,short,sources:renderMarkdown(sources,file),sourceCount:sourceIds.length,keywords:id===41?'Gödel Godel Turing connaissance logique calcul information limites intelligence':metadata.labs.filter(l=>l.questions.includes(id)).map(l=>l.title).join(' ')});
 }
 const registry=await readFile(resolve(root,'sources/README.md'),'utf8');
 const data={...metadata,questions,method:renderMarkdown(await readFile(resolve(root,'METHODE.md'),'utf8'),'METHODE.md'),sources:renderMarkdown(registry,'sources/README.md'),schemaVersion:1};
 await writeFile(resolve(root,'atlas/data.js'),'// Generated by npm run build. Edit questions/*.md or content/ instead.\nwindow.ATLAS_DATA = '+JSON.stringify(data).replace(/</g,'\\u003c')+';\n');
 return data;
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const d=await build();console.log(`Atlas built: ${d.questions.length} questions, ${d.questions.filter(q=>q.researched).length} research dossier, ${d.labs.length} laboratories.`);}
