import {readFile,writeFile,readdir,mkdir,copyFile,rm,stat} from 'node:fs/promises';
import {resolve,dirname,extname,relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import {build,root} from './build-atlas.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const out=resolve(root,'build/public');
const googleTag = `<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-L659XPNBR6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-L659XPNBR6');
</script>`;

async function addGoogleTag(directory) {
 for (const entry of await readdir(directory, {withFileTypes:true})) {
  const path = resolve(directory, entry.name);
  if (entry.isDirectory()) await addGoogleTag(path);
  else if (entry.name.endsWith('.html')) {
   const html = await readFile(path, 'utf8');
   if (!html.includes('<head>')) throw Error('Missing head for analytics: '+path);
   await writeFile(path, html.replace('<head>', '<head>'+googleTag));
  }
 }
}
export async function buildPublic(siteURL=process.env.SITE_URL||''){
 let base='';if(siteURL){const url=new URL(siteURL);if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash)throw Error('SITE_URL must be an HTTPS base address without credentials, query or fragment.');base=url.href.replace(/\/$/,'')+'/';}
 const data=await build();
 await mkdir(resolve(root,'build'),{recursive:true});
 try{await stat(out);await readFile(resolve(out,'.the42laws-build'));await rm(out,{recursive:true});}catch(error){if(error.code!=='ENOENT')throw error;try{await stat(out);throw Error('Existing public directory has no build marker; refusing to replace it.');}catch(check){if(check.code!=='ENOENT')throw check;}}
 await mkdir(out,{recursive:true});await writeFile(resolve(out,'.the42laws-build'),'Generated by scripts/build-public.mjs\n');
 async function copy(path){const from=resolve(root,path),to=resolve(out,path);await mkdir(dirname(to),{recursive:true});await copyFile(from,to);}
 for(const f of ['index.html','METHODE.md','QUESTIONS.md'])await copy(f);
 // Explicit public folders only. Runtime assets and research Markdown are public content.
 for(const folder of ['atlas','neutrino','antimatiere','photon','temps','navier-stokes','questions','sources','notes']){
  let files=[];try{files=await readdir(resolve(root,folder),{withFileTypes:true});}catch(e){if(e.code==='ENOENT')continue;throw e;}
  for(const f of files)if(f.isFile()&&/\.(html|css|js|svg|png|md)$/.test(f.name))await copy(folder+'/'+f.name);
 }
 const head=(title,description,path)=>`<meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:locale" content="fr_FR"><meta name="twitter:card" content="summary_large_image">${base?`<link rel="canonical" href="${esc(new URL(path,base).href)}"><meta property="og:url" content="${esc(new URL(path,base).href)}"><meta property="og:image" content="${esc(new URL('atlas/share-card.png',base).href)}"><meta name="twitter:image" content="${esc(new URL('atlas/share-card.png',base).href)}">`:''}`;
 for(const path of ['index.html',...data.labs.map(l=>l.url)]){const target=resolve(out,path);let html=await readFile(target,'utf8');const title=html.match(/<title>(.*?)<\/title>/s)?.[1]||'The42laws',description=html.match(/<meta name="description" content="([^"]*)"/)?.[1]||'Un atlas du réel.';html=html.replace(/<meta name="description" content="[^"]*">/,'').replace('</head>',head(title,description,path.replace(/index\.html$/,''))+'</head>');await writeFile(target,html);}
 const directory=data.questions.map(q=>`<a class="question-row" href="dossiers/${q.id}/"><span class="question-number">${String(q.id).padStart(2,'0')}</span><h2>${esc(q.title)}</h2><span class="badge">${esc(q.status)}</span></a>`).join('');
 const documents=[...data.questions.map(q=>({path:`dossiers/${q.id}/`,title:q.title,description:`Question ${q.id} — ${q.status}. Une exploration sourcée dans The42laws.`,body:`<a class="eyebrow" href="index.html#/atlas">← LES 42 QUESTIONS</a><h1>${esc(q.title)}</h1><p><span class="badge ready">${esc(q.status)}</span></p>${q.researched?`<div class="notice">Lecture courte d’un dossier provisoire. Les hypothèses et niveaux de consultation des sources restent à examiner dans la version complète.</div><article class="prose">${q.short?.html||'<p>Le dossier complet est disponible dans l’atlas.</p>'}</article>`:'<p class="muted">Cette fiche reste à explorer. Aucune synthèse n’est publiée pour le moment.</p>'}<div class="actions"><a class="button primary" href="index.html#/question/${q.id}">Ouvrir le lecteur et ses sources ↗</a><a class="button" href="dossiers/">Toutes les questions ↗</a></div>`})),{path:'dossiers/',title:'Les 42 questions — The42laws',description:'Le répertoire des 42 questions du projet The42laws.',body:'<h1>Les 42 questions.</h1><p>Un répertoire accessible sans JavaScript.</p>'+directory.replaceAll('href="dossiers/','href="dossiers/')}];
 for(const doc of documents){const target=resolve(out,doc.path,'index.html'),depth=doc.path.split('/').filter(Boolean).length,prefix='../'.repeat(depth);await mkdir(dirname(target),{recursive:true});await writeFile(target,`<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><base href="${prefix}"><title>${esc(doc.title)}</title>${head(doc.title,doc.description,doc.path)}<link rel="icon" href="atlas/icon.svg"><link rel="stylesheet" href="atlas/style.css"><link rel="stylesheet" href="atlas/features.css"></head><body><a class="skip" href="${doc.path}#reading">Aller au contenu</a><main class="page" id="reading" style="max-width:1000px">${doc.body}</main><footer class="footer"><a href="index.html#/accueil">THE42LAWS</a><a href="index.html#/apropos">Le projet ↗</a></footer></body></html>`);}
 await writeFile(resolve(out,'404.html'),'<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Page introuvable — The42laws</title></head><body><h1>Reprenons le fil.</h1><p>Cette page n’existe pas.</p><a href="'+esc(base||'/')+'">Retour à l’atlas</a></body></html>');
 const routes=['',...data.labs.map(l=>l.url.replace('index.html','')),...documents.map(d=>d.path)];
 await writeFile(resolve(out,'robots.txt'),'User-agent: *\nAllow: /\n'+(base?'Sitemap: '+new URL('sitemap.xml',base).href+'\n':''));
 if(base)await writeFile(resolve(out,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.map(r=>'<url><loc>'+esc(new URL(r,base).href)+'</loc></url>').join('')+'</urlset>');
 await writeFile(resolve(out,'_headers'),'/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: SAMEORIGIN\n');
 await writeFile(resolve(out,'publication.json'),JSON.stringify({application:'The42laws',version:2,baseURL:base||null,questions:42,researchDossiers:data.questions.filter(q=>q.researched).length,laboratories:data.labs.length,note:'Build statique. Aucun carnet personnel, fichier de travail IA ou secret inclus.'},null,2));
 // Only the hosted build receives analytics; local source previews stay offline.
 if(base) await addGoogleTag(out);
 return {out,routes,base};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const result=await buildPublic();console.log(`Public build: ${result.out}\n${result.routes.length} static routes. ${result.base?'Canonical URLs and sitemap configured.':'No domain configured; canonical URLs and sitemap omitted.'}`);}
