(function(){
'use strict';
const D=window.ATLAS_DATA,C=window.AtlasCore,E=C.escape,$=s=>document.querySelector(s),KEY='the42laws:v1';
let state=C.cleanState({}),storageAvailable=true,toastTimer;
try{state=C.cleanState(JSON.parse(localStorage.getItem(KEY)||'{}'));}catch{storageAvailable=false;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));storageAvailable=true;return true;}catch{storageAvailable=false;return false;}}
function toast(message){$('.toast').textContent=message;$('.toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('.toast').classList.remove('visible'),3200);}
const qBy=id=>D.questions.find(q=>q.id===Number(id));
const badge=q=>`<span class="badge ${q.researched?'ready':''}">${E(q.status)}</span>`;
const link=(href,text,primary=false)=>`<a class="button ${primary?'primary':''}" href="${E(href)}">${text} <span aria-hidden="true">↗</span></a>`;
function sidebar(active){
const nav=[['accueil','⌂','Vue d’ensemble'],['atlas','✳','Les 42 questions'],['laboratoires','⌘','Laboratoires'],['parcours','↝','Parcours guidés'],['carnet','▤','Mon carnet'],['methode','⊙','La méthode']];
$('#sidebar').innerHTML=`<a class="brand" href="#/accueil" aria-label="The42laws, accueil"><span class="brand-mark">42°</span><span class="brand-name">THE42LAWS<small>UN ATLAS DU RÉEL</small></span></a><nav class="side-nav" aria-label="Navigation principale">${nav.map(([id,icon,title])=>`<a href="#/${id}" ${active===id?'class="active" aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${title}</a>`).join('')}</nav><nav class="territories" aria-label="Les sept domaines"><span class="eyebrow">LES SEPT DOMAINES</span>${D.domains.map(d=>`<a class="domain-nav" href="#/atlas?d=${d.id}" style="--accent:${d.color}"><i aria-hidden="true"></i><span>${E(d.name)}</span><b>${String(d.range[1]-d.range[0]+1).padStart(2,'0')}</b></a>`).join('')}</nav><div class="side-bottom"><span>VOTRE EXPLORATION</span><div class="progress-track" aria-hidden="true"><i style="width:${state.read.length/42*100}%"></i></div><span>${state.read.length} / 42 dossiers marqués lus</span><br><a href="#/carnet">Carnet enregistré sur cet appareil ↗</a></div>`;
}
function constellation(){
let nodes='',lines='';
D.domains.forEach((d,g)=>{
 const angle=(g/7)*Math.PI*2-Math.PI/2,cx=210+125*Math.cos(angle),cy=210+125*Math.sin(angle),count=d.range[1]-d.range[0]+1;
 lines+=`<line x1="210" y1="210" x2="${cx}" y2="${cy}" stroke="${d.color}" opacity=".18"/>`;
 for(let k=0;k<count;k++){const a=k/count*Math.PI*2,x=cx+34*Math.cos(a),y=cy+34*Math.sin(a),q=qBy(d.range[0]+k);lines+=`<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="${d.color}" opacity=".24"/>`;nodes+=`<a href="#/question/${q.id}" aria-label="Question ${q.id} : ${E(q.title)}"><title>${E(q.title)}</title><circle cx="${x}" cy="${y}" r="5" fill="${d.color}"/><circle cx="${x}" cy="${y}" r="11" fill="transparent"/></a>`;}
 nodes+=`<a href="#/atlas?d=${d.id}" aria-label="Explorer ${E(d.name)}"><text x="${cx}" y="${cy+4}" text-anchor="middle" fill="${d.color}" font-size="11" font-family="Georgia">${d.roman}</text></a>`;
});
return `<div class="constellation"><svg viewBox="0 0 420 420" role="group" aria-label="Carte des 42 questions, regroupées en sept domaines"><circle cx="210" cy="210" r="170" fill="none" stroke="#30362d" stroke-dasharray="2 8"/><circle cx="210" cy="210" r="125" fill="none" stroke="#30362d"/><circle cx="210" cy="210" r="68" fill="none" stroke="#30362d"/>${lines}<text x="210" y="220" text-anchor="middle" fill="#edf0e7" font-size="46" font-family="Georgia">42</text><text x="210" y="240" text-anchor="middle" fill="#a0aa99" font-size="7" letter-spacing="2">QUESTIONS OUVERTES</text>${nodes}</svg><div class="constellation-caption"><span>CARTE DES QUESTIONS</span><span>CHAQUE POINT EST UNE ENTRÉE ↗</span></div></div>`;
}
function labCard(l){return `<a class="lab-card" href="${l.url}" style="--accent:${l.color}" data-lab="${l.id}"><span class="eyebrow">EXPÉRIENCE ${l.number} / PHYSIQUE FONDAMENTALE</span><div class="lab-art" aria-hidden="true"><svg viewBox="0 0 400 190"><defs><radialGradient id="glow-${l.id}"><stop stop-color="${l.color}" stop-opacity=".18"/><stop offset="1" stop-color="${l.color}" stop-opacity="0"/></radialGradient></defs><ellipse cx="200" cy="95" rx="180" ry="90" fill="url(#glow-${l.id})"/><g fill="none" stroke="${l.color}" stroke-opacity=".2"><ellipse cx="200" cy="95" rx="135" ry="30" transform="rotate(-23 200 95)"/><ellipse cx="200" cy="95" rx="90" ry="66"/><path d="M0 155L400 35M0 160L400 60M0 70L400 110"/></g><g fill="${l.color}"><circle cx="81" cy="122" r="3"/><circle cx="278" cy="37" r="2"/><circle cx="317" cy="92" r="3"/><circle cx="126" cy="49" r="2"/></g></svg><span>${l.symbol}</span></div><h3>${l.title}</h3><p>${l.subtitle}<br>Ouvrir le laboratoire interactif.</p><span class="arrow" aria-hidden="true">↗</span></a>`;}
function pathCards(){return `<div class="path-grid">${D.paths.map(p=>`<a class="path-card" href="#/parcours/${p.id}" style="--accent:${p.color}"><span class="path-symbol" aria-hidden="true">${p.symbol}</span><span class="eyebrow">${p.eyebrow}</span><h3>${p.title}</h3><p>${p.description}</p><small>${p.steps.length} ÉTAPES À EXPLORER →</small></a>`).join('')}</div>`;}
function home(){return `<div class="page">${state.last?`<a class="resume" href="#/question/${state.last}">Reprendre l’exploration <b>Question ${state.last} · ${E(qBy(state.last).title)} →</b></a>`:''}<section class="hero"><div><span class="eyebrow">UN CARNET DE RECHERCHE SUR L’EXISTENCE</span><h1>Le réel a encore<br><em>tout à nous<br>apprendre.</em></h1><p>42 grandes questions. Sept domaines à explorer.<br>Des expériences pour comprendre, des sources pour approfondir et le droit de ne pas encore savoir.</p><div class="actions">${link('#/atlas','Explorer les 42 questions',true)}${link('#/parcours/matiere','Par où commencer ?')}</div></div>${constellation()}</section><div class="stats-row"><div class="stat"><strong>42</strong><span>questions<br>pour interroger le réel</span></div><div class="stat"><strong>07</strong><span>domaines<br>qui se répondent</span></div><div class="stat"><strong>02</strong><span>laboratoires<br>pour expérimenter</span></div></div><section><div class="section-head"><div><span class="eyebrow">COMPRENDRE EN EXPLORANT</span><h2>Entrez dans le laboratoire.</h2></div><a href="#/laboratoires">Tout voir ↗</a></div><div class="lab-grid">${D.labs.map(labCard).join('')}</div></section><section class="feature"><span class="feature-symbol" aria-hidden="true">∞</span><div><span class="eyebrow">LE PREMIER DOSSIER · QUESTION 41</span><h3>Existe-t-il des limites à ce que l’on peut connaître ?</h3>${badge(qBy(41))}<p>Logique, calcul et connaissance. Une première synthèse à lire et à discuter.</p></div>${link('#/question/41','Lire le dossier')}</section><section><div class="section-head"><div><span class="eyebrow">SUIVRE UN FIL</span><h2>Une question en appelle une autre.</h2></div></div>${pathCards()}</section></div>`;}
function questionRow(q){return `<a class="question-row" href="#/question/${q.id}" style="--accent:${q.color}"><span class="question-number">${String(q.id).padStart(2,'0')}</span><h3>${E(q.title)}</h3><span class="row-meta">${state.saved.includes(q.id)?'<span aria-label="En favori">☆</span>':''}${state.read.includes(q.id)?'<span class="read-mark">Lu ✓</span>':''}${badge(q)}<span aria-hidden="true">↗</span></span></a>`;}
function atlas(params){let domain=D.domains.some(d=>d.id===params.get('d'))?params.get('d'):'all',status=['draft','ready'].includes(params.get('etat'))?params.get('etat'):'all';return `<div class="page"><div class="page-intro"><span class="eyebrow">SEPT DOMAINES · UN MÊME ÉTONNEMENT</span><h1>Les 42 questions.</h1><p>Une carte de ce que nous cherchons à comprendre. Chaque dossier indique son état de recherche : une question ouverte n’est pas une réponse acquise.</p></div><form class="filter-panel" id="filters" role="search"><div class="search-row"><input class="search-input" type="search" id="question-search" name="q" value="${E(params.get('q')||'')}" placeholder="Rechercher une question, un concept…" aria-label="Rechercher dans les 42 questions"><select id="status-filter" aria-label="État de recherche"><option value="all">Tous les états de recherche</option><option value="draft" ${status==='draft'?'selected':''}>À explorer</option><option value="ready" ${status==='ready'?'selected':''}>Synthèse provisoire</option></select></div><div class="chips" role="group" aria-label="Filtrer par domaine"><button class="chip" type="button" data-domain="all" aria-pressed="${domain==='all'}">Tous les domaines</button>${D.domains.map(d=>`<button type="button" class="chip" data-domain="${d.id}" aria-pressed="${domain===d.id}">${E(d.name)}</button>`).join('')}</div></form><div id="atlas-results"></div></div>`;}
function updateResults(sync=true){const domain=$('[data-domain][aria-pressed=true]').dataset.domain,query=$('#question-search').value,status=$('#status-filter').value,results=C.filterQuestions(D.questions,{query,domain,status});$('#atlas-results').innerHTML=`<p class="result-count" role="status">${results.length} question${results.length>1?'s':''} · ${results.filter(q=>q.researched).length} synthèse provisoire</p>${results.length?D.domains.map(d=>{const items=results.filter(q=>q.domain===d.id);return items.length?`<section class="question-group"><div class="group-heading" style="--accent:${d.color}"><span>${d.roman}</span><h2>${E(d.name)}</h2><small>${E(d.subtitle)}</small></div>${items.map(questionRow).join('')}</section>`:'';}).join(''):`<div class="empty"><h2>Aucune question trouvée.</h2><p>Essayez un autre mot ou élargissez les filtres.</p><button class="button" data-reset-filters>Réinitialiser les filtres</button></div>`}`;if(sync){const p=new URLSearchParams();if(domain!=='all')p.set('d',domain);if(query)p.set('q',query);if(status!=='all')p.set('etat',status);history.replaceState(null,'',`#/atlas${p.size?'?'+p:''}`);}}
function notes(q){return `<section class="note-box"><h2>Ce que cette question vous inspire.</h2><p>Vos notes restent dans ce navigateur. Retrouvez-les et exportez-les depuis votre carnet.</p><label for="personal-note" class="eyebrow">VOTRE NOTE PERSONNELLE</label><textarea id="personal-note" data-note="${q.id}" maxlength="50000" placeholder="Une intuition, une objection, une piste à creuser…">${E(state.notes[q.id]||'')}</textarea><span class="save-status" role="status">${storageAvailable?'Enregistrement automatique sur cet appareil.':'Stockage indisponible. Exportez votre carnet pour conserver vos notes.'}</span></section>`;}
function reading(doc){return `<div class="reading-layout"><article class="prose">${doc.html}</article><aside class="toc" aria-label="Sommaire du dossier"><span class="eyebrow">DANS CETTE LECTURE</span>${doc.headings.filter(h=>h.depth===2).map(h=>`<button data-scroll="${h.id}">${E(h.title)}</button>`).join('')}</aside></div>`;}
function question(q,params){const mode=['complet','sources'].includes(params.get('lecture'))?params.get('lecture'):'essentiel';let body='';if(q.researched){const doc=mode==='sources'?q.sources:mode==='complet'?{html:q.html,headings:q.headings}:q.short||{html:q.html,headings:q.headings};body=`<nav class="tabs" aria-label="Version du dossier">${[['essentiel','L’essentiel'],['complet','Dossier complet'],['sources',`Sources (${q.sourceCount})`]].map(([id,label])=>`<a href="#/question/${q.id}?lecture=${id}" ${mode===id?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="notice">${mode==='complet'?'Dossier de recherche original, conservé pour discussion. Certaines conclusions générales et conjectures dépassent les résultats démontrés. La vue « L’essentiel » en précise la portée ; cette publication ne vaut pas validation scientifique intégrale.':mode==='sources'?'Le niveau de consultation est indiqué pour chaque référence : texte, résumé ou repérage bibliographique. Une référence recensée n’implique pas qu’elle ait été lue intégralement.':'Une lecture courte et prudente de la synthèse. Les résultats dépendent de leurs hypothèses ; les questions plus générales restent ouvertes.'}</div>${reading(doc)}`;}else{const labs=D.labs.filter(l=>l.questions.includes(q.id));body=`<div class="empty"><span class="eyebrow">LE DOSSIER RESTE À CONSTRUIRE</span><h2>Commençons par poser la question.</h2><p>La recherche et la synthèse de ce dossier ne sont pas encore rédigées.<br>Vous pouvez noter vos pistes et explorer les liens ci-dessous.</p>${link('#/methode','Comment nous cherchons')}</div>${labs.length?`<div class="section-head"><h2>Expériences liées</h2></div><div class="lab-grid">${labs.map(labCard).join('')}</div>`:''}<div class="section-head"><h2>Dans le même domaine</h2></div>${D.questions.filter(x=>x.domain===q.domain&&x.id!==q.id).slice(0,3).map(questionRow).join('')}`;}
return `<div class="page"><div class="reader-head"><a class="eyebrow" href="#/atlas?d=${q.domain}">← ${E(q.domainName)} / QUESTION ${String(q.id).padStart(2,'0')}</a><h1>${E(q.title)}</h1><div class="reader-meta">${badge(q)}${q.updated?`<span>Mise à jour du dossier : ${E(q.updated)}</span>`:''}<a href="${q.file}" download>Fichier de recherche ↗</a></div><div class="reader-actions"><button class="button" data-save="${q.id}" aria-pressed="${state.saved.includes(q.id)}">${state.saved.includes(q.id)?'★ Dans mes favoris':'☆ Ajouter aux favoris'}</button><button class="button" data-read="${q.id}" aria-pressed="${state.read.includes(q.id)}">${state.read.includes(q.id)?'✓ Marqué comme lu':'Marquer comme lu'}</button></div></div>${body}${notes(q)}<nav class="prev-next" aria-label="Questions adjacentes">${q.id>1?`<a href="#/question/${q.id-1}">← Question ${q.id-1}</a>`:'<span></span>'}<a href="#/atlas">Les 42 questions</a>${q.id<42?`<a href="#/question/${q.id+1}">Question ${q.id+1} →</a>`:'<span></span>'}</nav></div>`;}
function laboratories(){return `<div class="page"><div class="page-intro"><span class="eyebrow">MANIPULER POUR COMPRENDRE</span><h1>Le laboratoire du réel.</h1><p>Deux explorations interactives pour passer d’une idée à une expérience. Chaque laboratoire expose ses hypothèses, les limites de son modèle et ses sources.</p></div><div class="lab-grid">${D.labs.map(labCard).join('')}</div><div class="notice" style="margin-top:30px">Les portraits sont des évocations artistiques. Les calculs et les modèles pédagogiques sont expliqués dans chaque laboratoire.</div><div class="section-head"><h2>Relier les expériences</h2></div>${pathCards()}</div>`;}
function paths(id){const p=D.paths.find(x=>x.id===id);if(id&&!p)return notFound();if(!p)return `<div class="page"><div class="page-intro"><span class="eyebrow">APPRENDRE EN SUIVANT UN FIL</span><h1>Choisissez votre point de départ.</h1><p>Trois itinéraires à votre rythme. Ils relient les expériences disponibles aux questions de recherche, dont certaines attendent encore leur synthèse.</p></div>${pathCards()}</div>`;return `<div class="page"><div class="page-intro"><a class="eyebrow" href="#/parcours">← LES PARCOURS</a><h1>${p.title}</h1><p>${p.description}</p></div>${p.steps.map((s,i)=>{const item=s.type==='lab'?D.labs.find(l=>l.id===s.id):qBy(s.id),done=s.type==='lab'?state.labs.includes(s.id):state.read.includes(s.id);return `<article class="step" style="--accent:${p.color}"><span>${String(i+1).padStart(2,'0')}</span><div><span class="eyebrow">${s.type==='lab'?'LABORATOIRE INTERACTIF':`QUESTION ${item.id}`}${done?' · '+(s.type==='lab'?'DÉJÀ OUVERT':'MARQUÉ LU'):''}</span><h2>${E(item.title)}</h2>${s.type==='lab'?`<p>${item.description}</p>`:badge(item)}</div><a class="button" href="${s.type==='lab'?item.url:'#/question/'+item.id}" ${s.type==='lab'?`data-lab="${item.id}"`:''}>${s.type==='lab'?'Expérimenter':'Explorer'} ↗</a></article>`;}).join('')}</div>`;}
function notebook(){const ids=Object.keys(state.notes).filter(id=>state.notes[id].trim());return `<div class="page"><div class="page-intro"><span class="eyebrow">VOTRE ESPACE DE RÉFLEXION</span><h1>Mon carnet.</h1><p>Vos questions favorites, votre progression de lecture et vos notes. Ce carnet est conservé dans ce navigateur, sans compte ni synchronisation.</p><button class="button" data-export>Exporter mon carnet ↓</button></div>${!storageAvailable?'<div class="notice">Le stockage local est indisponible. Exportez le carnet avant de quitter cette page pour conserver vos notes.</div>':''}<div class="notebook-stats"><div><strong>${state.saved.length}</strong><span>favoris</span></div><div><strong>${state.read.length}</strong><span>dossiers marqués lus</span></div><div><strong>${ids.length}</strong><span>notes personnelles</span></div></div><div class="section-head"><h2>Mes favoris</h2></div>${state.saved.length?D.questions.filter(q=>state.saved.includes(q.id)).map(questionRow).join(''):'<div class="empty"><p>Aucun favori pour le moment. Ouvrez une question et ajoutez-la à votre carnet.</p>'+link('#/atlas','Parcourir les questions')+'</div>'}<div class="section-head"><h2>Mes notes</h2></div>${ids.length?ids.map(id=>`<section>${questionRow(qBy(id))}<p class="note-preview">${E(state.notes[id])}</p></section>`).join(''):'<p class="muted">Une zone de notes vous attend à la fin de chaque question.</p>'}${state.read.length?`<div class="section-head"><h2>Mes lectures</h2></div>${D.questions.filter(q=>state.read.includes(q.id)).map(questionRow).join('')}`:''}</div>`;}
function notFound(){return `<div class="page"><div class="empty"><span class="eyebrow">CHEMIN INCONNU</span><h1>Reprenons le fil.</h1><p>Cette page n’existe pas dans l’atlas.</p>${link('#/atlas','Retrouver les 42 questions',true)}</div></div>`;}
function closeMenu(){$('#sidebar').inert=innerWidth<=800;const wasOpen=$('#sidebar').classList.contains('open');$('#sidebar').classList.remove('open');$('.veil').hidden=true;$('.menu-button').setAttribute('aria-expanded','false');$('.menu-button').setAttribute('aria-label','Ouvrir le menu');if(wasOpen)document.body.style.overflow='';}
function render(){closeMenu();const {parts,params}=C.parseRoute(location.hash),route=parts[0];sidebar(route==='question'?'atlas':route);let html,title='Un atlas du réel';switch(route){case'accueil':html=home();break;case'atlas':html=atlas(params);title='Les 42 questions';break;case'question':{const q=qBy(parts[1]);if(!q){html=notFound();break;}state.last=q.id;persist();html=question(q,params);title=`Question ${q.id} — ${q.title}`;break;}case'laboratoires':html=laboratories();title='Laboratoires';break;case'parcours':html=paths(parts[1]);title='Parcours guidés';break;case'carnet':html=notebook();title='Mon carnet';break;case'methode':case'sources':{title=route==='methode'?'Notre méthode':'Registre des sources';const doc=route==='methode'?D.method:D.sources;html=`<div class="page"><div class="page-intro"><span class="eyebrow">LA RECHERCHE EN CLAIR</span><h1>${title}</h1><p>${route==='methode'?'Distinguer ce qui est observé, démontré, proposé ou encore inconnu.': 'Un registre de travail. Les dates et niveaux de consultation précisent l’état documentaire de chaque référence.'}</p>${link(route==='methode'?'#/sources':'#/methode',route==='methode'?'Consulter les sources':'Comprendre la méthode')}</div>${reading(doc)}</div>`;break;}default:html=notFound();title='Page introuvable';}
$('#main').innerHTML=html;document.title=`${title} — The42laws`;$('.breadcrumb').textContent=route==='question'?'ATLAS / DOSSIER DE RECHERCHE':title.toUpperCase();if(route==='atlas')updateResults(false);window.scrollTo(0,0);$('#main').focus({preventScroll:true});if(route==='atlas'&&params.get('focus')==='search')$('#question-search').focus();}
document.addEventListener('click',e=>{
const t=e.target.closest('button,a');if(!t)return;
if(t.matches('.menu-button')){const open=t.getAttribute('aria-expanded')==='true';if(open)closeMenu();else{$('#sidebar').inert=false;$('#sidebar').classList.add('open');$('.veil').hidden=false;t.setAttribute('aria-expanded','true');t.setAttribute('aria-label','Fermer le menu');document.body.style.overflow='hidden';$('#sidebar a').focus();}return;}
if(t.matches('.veil')){closeMenu();$('.menu-button').focus();return;}
if(t.matches('.skip')){e.preventDefault();$('#main').focus();return;}
if(t.dataset.domain){$$('[data-domain]').forEach(b=>b.setAttribute('aria-pressed',String(b===t)));updateResults();return;}
if(t.hasAttribute('data-reset-filters')){$('#question-search').value='';$('#status-filter').value='all';$$('[data-domain]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.domain==='all')));updateResults();$('#question-search').focus();return;}
if(t.dataset.scroll){document.getElementById(t.dataset.scroll)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});document.getElementById(t.dataset.scroll)?.focus({preventScroll:true});return;}
if(t.dataset.lab){if(!state.labs.includes(t.dataset.lab))state.labs.push(t.dataset.lab);persist();}
if(t.dataset.save||t.dataset.read){const save=!!t.dataset.save,id=Number(t.dataset.save||t.dataset.read),key=save?'saved':'read';state[key]=state[key].includes(id)?state[key].filter(x=>x!==id):[...state[key],id];const ok=persist(),enabled=state[key].includes(id);t.setAttribute('aria-pressed',String(enabled));t.textContent=save?(enabled?'★ Dans mes favoris':'☆ Ajouter aux favoris'):(enabled?'✓ Marqué comme lu':'Marquer comme lu');sidebar('atlas');toast(ok?'Carnet enregistré.':'Stockage indisponible : pensez à exporter votre carnet.');return;}
if(t.hasAttribute('data-export')){const blob=new Blob([JSON.stringify({application:'The42laws',exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`the42laws-carnet-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Export du carnet préparé.');}
});
const $$=s=>[...document.querySelectorAll(s)];
document.addEventListener('input',e=>{if(e.target.id==='question-search')updateResults();if(e.target.dataset.note){state.notes[e.target.dataset.note]=e.target.value;const ok=persist();$('.save-status').textContent=ok?'Note enregistrée sur cet appareil.':'Stockage indisponible : exportez le carnet pour conserver cette note.';}});
document.addEventListener('change',e=>{if(e.target.id==='status-filter')updateResults();});
document.addEventListener('submit',e=>{if(e.target.id==='filters'){e.preventDefault();updateResults();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape') {closeMenu();if(innerWidth<=800)$('.menu-button').focus();}if(e.key==='Tab'&&$('#sidebar').classList.contains('open')){const links=$$('#sidebar a'),first=links[0],last=links.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
addEventListener('hashchange',render);addEventListener('pageshow',e=>{if(e.persisted){try{state=C.cleanState(JSON.parse(localStorage.getItem(KEY)||'{}'));}catch{}render();}});addEventListener('resize',()=>{if(innerWidth>800)closeMenu();else if(!$('#sidebar').classList.contains('open'))$('#sidebar').inert=true;});render();
})();
