(function(root){
 'use strict';
 const C=typeof module==='object'&&module.exports?require('./core.js'):root.AtlasCore;
 const KEY='the42laws:consent:v1',AGE=180*86400000;
 function validChoice(value,now=Date.now()){return value?.version===1&&typeof value.analytics==='boolean'&&Number.isFinite(value.updatedAt)&&value.updatedAt<=now&&now-value.updatedAt<AGE;}
 function safePage(loc){const p=loc.pathname.replace(/index\.html$/,'');const hash=loc.hash||'';const route=/^#\/(accueil|atlas|laboratoires|particules|liens|parcours|glossaire|methode|sources|apropos)(?:\/([a-z-]+))?(?:\?|$)/.exec(hash);if(route?.[2]&&(route[1]!=='parcours'||!['matiere','temps','connaitre','fondements','origines-vie'].includes(route[2])))return null;if((p==='/'&&hash||hash.startsWith('#/'))&&!route)return null;if(C?.questionId(p)!==null&&C?.questionId(p)!==undefined)return loc.origin+C.questionPath(C.questionId(p));if(/^\/(laboratoires|glossaire|methode|sources|parcours|particules|liens|apropos)\/$/.test(p)||/^\/parcours\/(matiere|temps|connaitre|fondements|origines-vie)\/$/.test(p)||/^\/domaines\/(existence|realite|physique|univers|vie|conscience|sens)\/$/.test(p)||/^\/dossiers\/(?:[1-9]|[1-3][0-9]|4[0-2])\/$/.test(p)||/^\/(neutrino|antimatiere|photon|temps|navier-stokes|relativite|trou-noir|confidentialite|mentions-legales)\/$/.test(p)||p==='/dossiers/'||p==='/')return loc.origin+p+(route?'#/'+route[1]+(route[2]?'/'+route[2]:''):'');return null;}
 if(typeof module==='object'&&module.exports){module.exports={validChoice,safePage};return;}
 const doc=root.document,script=doc.querySelector('script[src="/atlas/consent.js"]'),id=script?.dataset.measurementId||'',enabled=/^G-[A-Z0-9]+$/.test(id);let choice=null,choiceStored=true,loaded=false,lastPage=null;
 try{const value=JSON.parse(localStorage.getItem(KEY));if(validChoice(value))choice=value;}catch{}
 function clearCookies(){for(const cookie of doc.cookie.split(';')){const name=cookie.trim().split('=')[0];if(!/^_ga(?:_|$)/.test(name))continue;for(const domain of ['',...location.hostname.split('.').map((_,i,a)=>'.'+a.slice(i).join('.'))])doc.cookie=name+'=; Max-Age=0; path=/'+(domain?'; domain='+domain:'')+'; SameSite=Lax';}}
 function refreshChoice(){let next=choice;try{if(!choiceStored)return true;const stored=JSON.parse(localStorage.getItem(KEY));next=validChoice(stored)?stored:null;}catch{}if(!next?.analytics&&loaded){root['ga-disable-'+id]=true;clearCookies();location.reload();return false;}choice=next;if(!choice&&enabled)show();return true;}
 function page(){if(!refreshChoice()||!choice?.analytics)return;if(!loaded){if(safePage(location))load();return;}if(!validChoice(choice)){choose(false);return;}const url=safePage(location);root.gtag('set',{page_location:url||location.origin+'/',page_title:url?doc.title:'The42laws',page_referrer:''});root['ga-disable-'+id]=!url;if(!url){lastPage=null;return;}if(url===lastPage)return;lastPage=url;root.gtag('event','page_view',{page_location:url,page_title:doc.title,page_referrer:''});}
 function load(){if(!enabled||loaded||!safePage(location))return;loaded=true;root['ga-disable-'+id]=false;root.dataLayer=root.dataLayer||[];root.gtag=function(){root.dataLayer.push(arguments);};root.gtag('consent','default',{analytics_storage:'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});root.gtag('set','ads_data_redaction',true);root.gtag('consent','update',{analytics_storage:'granted',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});root.gtag('js',new Date());root.gtag('set',{page_location:safePage(location),page_title:doc.title,page_referrer:''});root.gtag('config',id,{send_page_view:false,allow_google_signals:false,allow_ad_personalization_signals:false,cookie_expires:15552000,cookie_update:false});const tag=doc.createElement('script');tag.async=true;tag.referrerPolicy='no-referrer';tag.src='https://www.googletagmanager.com/gtag/js?id='+id;tag.id='the42laws-google-tag';doc.head.append(tag);page();}
 const banner=doc.createElement('section');banner.className='consent-banner';banner.setAttribute('aria-label','Choix de mesure d’audience');banner.setAttribute('tabindex','-1');banner.innerHTML='<div><strong>Votre exploration, votre choix.</strong><p>Google Analytics nous aide à comprendre les pages consultées. Il ne se charge qu’avec votre accord. Votre carnet reste sur cet appareil. <a href="/confidentialite/">Confidentialité</a></p></div><div class="consent-actions"><button type="button" data-consent="no">Refuser</button><button type="button" data-consent="yes">Accepter Analytics</button></div><p class="consent-status" role="status"></p>';doc.body.append(banner);
 function show(){banner.hidden=false;banner.querySelector('[data-consent="yes"]').hidden=!enabled;banner.querySelector('[data-consent="no"]').textContent=enabled?'Refuser':'Fermer (mesure désactivée en aperçu)';}
 function choose(analytics){choice={version:1,analytics:enabled&&analytics,updatedAt:Date.now()};let saved=true;try{localStorage.setItem(KEY,JSON.stringify(choice));}catch{saved=false;banner.querySelector('.consent-status').textContent='Choix appliqué pour cette page ; le stockage de ce navigateur ne permet pas de le mémoriser.';}choiceStored=saved;banner.hidden=saved;if(choice.analytics)load();else{root['ga-disable-'+id]=true;clearCookies();if(loaded){root.gtag('consent','update',{analytics_storage:'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});if(saved)location.reload();}}}
 banner.querySelector('[data-consent="no"]').addEventListener('click',()=>choose(false));
 banner.querySelector('[data-consent="yes"]').addEventListener('click',()=>choose(true));
 const bound=new WeakSet();function bindPreferences(){for(const button of doc.querySelectorAll('[data-cookie-settings]'))if(!bound.has(button)){bound.add(button);button.addEventListener('click',()=>{show();banner.focus();});}}bindPreferences();
 root.addEventListener('the42laws:route',()=>{bindPreferences();page();});root.addEventListener('storage',e=>{if(e.key!==KEY)return;choiceStored=true;let next=null;try{next=JSON.parse(e.newValue);}catch{}if(!validChoice(next)||!next.analytics){choice=next;root['ga-disable-'+id]=true;clearCookies();if(loaded)location.reload();else if(!validChoice(next))show();}else{choice=next;banner.hidden=true;load();}});
 root.addEventListener('pageshow',()=>{if(refreshChoice()&&choice?.analytics)load();});
 if(choice){banner.hidden=true;if(choice.analytics)load();else clearCookies();}else if(enabled)show();else banner.hidden=true;
})(globalThis);
