(function(){
 'use strict';
 const guides={
  relativite:{id:'horloges',title:'Changer de vitesse, garder la durée terrestre',question:10,predict:'Pour un aller-retour de 10 ans sur Terre, passer de 0,60 c à 0,80 c augmente-t-il ou diminue-t-il la durée vécue à bord ?',change:'Appliquez 0,60 c et 10 ans. Cliquez sur « Voir le retour », puis relevez A. Choisissez 0,80 c, cliquez de nouveau sur « Voir le retour » et relevez B.',observe:'Comparez les deux durées au même événement de retrouvailles. Vérifiez aussi que la distance du demi-tour a changé.',explain:'Calculez √(1 − β²) pour les deux vitesses. Pourquoi le voyageur et la Terre ne suivent-ils pas des trajets symétriques ?',limit:'Relativité restreinte sans gravitation. Le demi-tour instantané est une idéalisation ; le diagramme ne montre pas les signaux lumineux reçus.',answer:'À 0,60 c, le voyageur mesure 8 ans ; à 0,80 c, il mesure 6 ans, contre 10 ans sur Terre dans les deux cas. Le demi-tour passe de 3 à 4 années-lumière. La durée propre dépend du trajet entre les deux événements communs.',set:{speed:0.6,duration:10},reset:'reset',metrics:{'earth-time':'Temps terrestre','traveler-time':'Temps voyageur','final-gap':'Écart au retour','turn-distance':'Distance du demi-tour'}},
  photon:{id:'chemins',title:'Quand les franges disparaissent',question:19,predict:'Une information permettant de distinguer les chemins peut-elle changer les franges, même sans lecture humaine ?',change:'Appliquez le réglage initial, ajoutez 500 impacts avec « + 100 impacts » cinq fois et relevez A. Cochez « Information de chemin accessible », recommencez les impacts et relevez B.',observe:'Comparez la forme de la courbe théorique et celle des impacts, pas seulement leur nombre.',explain:'Expliquez pourquoi une somme de probabilités diffère du carré d’une somme d’amplitudes.',limit:'Ce tirage simule une distribution. Il ne sélectionne aucune interprétation de la mesure et ne représente pas un observateur conscient.',answer:'Quand les chemins sont distinguables, le terme d’interférence est absent dans ce modèle. Avec peu de points, les fluctuations peuvent masquer la forme attendue. La décohérence et le problème du résultat unique sont deux questions distinctes.',set:{wavelength:550,separation:180,'which-path':false},click:'[data-slits="2"]',reset:'reset',metrics:{count:'Impacts',energy:'Énergie',fringe:'Interfrange'}},
  temps:{id:'entropie',title:'La préparation change l’histoire',question:25,predict:'Avec les mêmes règles, partir d’un état équilibré donne-t-il la même évolution que partir avec tous les objets à gauche ?',change:'Appliquez le départ à gauche et faites 50 transitions ; relevez A. Choisissez ensuite « Moitié de chaque côté », faites 50 transitions et relevez B.',observe:'Observez la courbe entière : l’entropie peut baisser sur certaines transitions.',explain:'Expliquez le rôle du nombre de configurations et ce que le modèle ne dit pas sur le choix de l’état initial.',limit:'Aucune gravitation ni expansion dans ces urnes. Rejouer l’historique ne remonte pas le temps cosmologique.',answer:'Les mêmes transitions favorisent statistiquement les macroétats les plus nombreux, mais le départ détermine la trajectoire initiale. À l’équilibre, le système continue de fluctuer ; l’entropie n’augmente pas à chaque pas.',set:{'object-count':'40',initial:'left'},reset:'reset',metrics:{'left-count':'Objets à gauche',entropy:'S / k_B',multiplicity:'Configurations','history-value':'Transitions'}},
  neutrino:{id:'oscillations',title:'Doubler la distance et l’énergie',question:15,predict:'Que deviennent les probabilités si l’on double à la fois la distance et l’énergie ?',change:'Appliquez 500 km et 1 GeV ; relevez A. Passez à 1 000 km et 2 GeV, puis relevez B.',observe:'Comparez les trois probabilités, et vérifiez que leur somme est proche de 100 %. Les arrondis peuvent masquer une petite différence.',explain:'Reliez les résultats au rapport L/E, puis dites pourquoi une saveur ne se transforme pas selon un cycle obligatoire.',limit:'Oscillations dans le vide avec paramètres fixés ; pas d’effet de matière terrestre, de détecteur ni de flux solaire.',answer:'Dans ce modèle de propagation dans le vide, les phases relatives dépendent de L/E. Le même rapport redonne les mêmes probabilités. Il s’agit de probabilités de détection, pas d’une suite imposée électronique → muonique → tauique.',set:{energy:1,distance:500},click:'[data-flavor="1"]',metrics:{'prob-0':'Électronique','prob-1':'Muonique','prob-2':'Tauique'}},
  antimatiere:{id:'energie',title:'Où va l’énergie de la paire ?',question:25,predict:'Au repos, une annihilation libère-t-elle une énergie nulle ? Et si chaque particule reçoit 0,5 MeV d’énergie cinétique ?',change:'Appliquez le repos et relevez A. Réglez ensuite 0,5 MeV par particule et relevez B. Lancez les annihilations pour regarder le schéma.',observe:'Comparez l’énergie totale et l’énergie par photon, en faisant attention aux unités MeV et keV.',explain:'Additionnez les deux énergies de masse et les deux énergies cinétiques. Expliquez pourquoi cette conservation ne crée pas un excès initial de matière.',limit:'Canal à deux photons dans le référentiel du centre de masse, pas tous les canaux possibles ni une simulation de baryogenèse.',answer:'Au repos, la paire possède déjà environ 1,022 MeV d’énergie de masse : environ 511 keV pour chacun des deux photons. Ajouter 0,5 MeV à chaque particule porte le total à environ 2,022 MeV.',set:{kinetic:0},reset:'reset',metrics:{'total-energy':'Énergie totale','photon-energy':'Par photon',wavelength:'Longueur d’onde'}},
  'navier-stokes':{id:'dissipation',title:'Une référence pour tester le fluide',question:23,predict:'Sans force ni effet visuel de confinement, l’énergie de Taylor-Green reste-t-elle constante lorsque la viscosité est positive ?',change:'Appliquez Taylor-Green et relevez A à t = 0. Appuyez cinq fois sur « +10 pas », puis relevez B. Gardez la viscosité initiale et n’agissez pas sur le canevas.',observe:'Comparez l’énergie calculée, la référence théorique et l’écart numérique. Le calcul 2D et la grille finie ont leurs limites.',explain:'Distinguez dissipation visqueuse, erreur numérique et force extérieure. Pourquoi une animation ne prouve-t-elle pas une singularité 3D ?',limit:'Domaine 2D périodique. Le confinement ajoute une force visuelle ; le masque d’obstacle n’est pas un solveur rigoureux de paroi incompressible. Le schéma d’explosion reste illustratif.',answer:'La référence décroît comme exp(−4νt) pour l’énergie. Le schéma numérique peut dissiper davantage ; une concordance approchée est un contrôle utile, pas une démonstration du problème du millénaire.',set:{confinement:0},click:'[data-preset="taylor-green"]',metrics:{'stat-time':'Temps','stat-energy':'Énergie','stat-theory':'Référence','stat-gap':'Écart'}}
 };
 guides['trou-noir']={id:'horizon',title:'Deux masses, deux horizons',question:21,predict:'Si la masse passe de 10 à 20 masses solaires, le rayon de l’horizon double-t-il aussi ?',change:'Appliquez 10 masses solaires et relevez A. Cliquez sur « 20 soleils » dans les commandes et relevez B. Gardez le même grossissement.',observe:'Comparez le rayon en kilomètres. La scène garde la même échelle en unités de rayon : la taille de l’image ne permet pas de comparer les deux rayons physiques.',explain:'À partir de rₛ = 2GM / c², expliquez pourquoi doubler M double rₛ lorsque G et c restent constants.',answer:'Pour 10 masses solaires, rₛ vaut environ 29,53 km ; pour 20, environ 59,07 km. M est multipliée par deux dans la même formule, donc le rayon double. Ce résultat concerne un trou noir sans rotation et sans charge.',limit:'Rayon de Schwarzschild sans rotation ni charge. La scène est une interprétation artistique, pas une mesure de l’horizon ni un calcul complet de relativité générale.',set:{mass:10,inclination:12,zoom:1,exposure:1.25,disk:true,palette:'amber'},metrics:{'bh-mass-value':'Masse','bh-radius':'Rayon de Schwarzschild'}};
 const lab=location.pathname.split('/').filter(Boolean)[0],g=guides[lab];if(!g||!window.AtlasNotebook)return;
 const controls={relativite:['speed','duration','progress'],photon:['wavelength','separation','which-path','show-theory'],temps:['object-count','initial'],neutrino:['energy','distance'],antimatiere:['kinetic','excess'],'navier-stokes':['viscosity','confinement','force-strength','quality','tau-slider','h-slider']};
 const modes={photon:['slits'],neutrino:['flavor'],'navier-stokes':['preset','view']};
 const key=lab+':'+g.id,esc=AtlasCore.escape;
 function mount(){if(document.getElementById('guide'))return;const anchor=document.getElementById('experience')||document.getElementById('laboratoire');if(!anchor||lab==='trou-noir'&&!document.getElementById('bh-model-state'))return false;
 const panel=document.createElement('section');panel.className='guided-experience';panel.id='guide';panel.setAttribute('aria-label','Expérience guidée');
 panel.innerHTML=`<span class="guide-kicker">EXPÉRIENCE GUIDÉE · 10 MIN ENVIRON</span><h2>${esc(g.title)}</h2><ol><li><h3>1. Faites une prédiction</h3><label for="guide-prediction">${esc(g.predict)}</label><textarea id="guide-prediction" maxlength="3000" placeholder="Je pense que… parce que…"></textarea></li><li><h3>2. Changez un paramètre</h3><p>${esc(g.change)}</p><button type="button" data-guide-setup>Appliquer le réglage initial</button><a href="#${anchor.id}">Aller aux commandes ↓</a></li><li><h3>3. Observez et comparez</h3><p>${esc(g.observe)}</p><div class="guide-actions"><button type="button" data-guide-capture="A">Relever A</button><button type="button" data-guide-capture="B">Relever B</button></div><div id="guide-results"></div></li><li><h3>4. Expliquez le résultat</h3><label for="guide-explanation">${esc(g.explain)}</label><textarea id="guide-explanation" maxlength="3000" placeholder="J’observe que… Ce modèle permet de dire…"></textarea><details><summary>Comparer avec une piste d’explication</summary><p>${esc(g.answer)}</p></details></li></ol><p class="guide-limit"><strong>Limite du modèle.</strong> ${esc(g.limit)}</p><div class="guide-actions"><button type="button" data-guide-save>Enregistrer dans mon carnet</button><button type="button" data-guide-resume>Restaurer mes derniers réglages</button><button type="button" data-guide-export>Exporter cette expérience</button><a href="/#/carnet">Ouvrir mon carnet →</a><a href="/dossiers/${g.question}/">Poursuivre avec le dossier ${g.question} →</a><a href="?guide=${g.id}#guide">Lien permanent</a></div><p class="guide-small">Réponses et relevés enregistrés sur cet appareil. La reprise restaure les paramètres ; les tirages aléatoires, l’historique et l’état du fluide ne sont pas rejoués. Le lien partage seulement le guide.</p><p id="guide-status" role="status"></p>`;
 anchor.before(panel);
 const status=msg=>panel.querySelector('#guide-status').textContent=msg;
 let stored=null,captures={},timer,restoring=false,createdAt=new Date().toISOString();
 try{stored=AtlasNotebook.read().experiences[key];}catch{status('Stockage indisponible. Exportez votre expérience pour la conserver.');}
 function settings(){if(lab==='trou-noir'){try{const {playing,...values}=JSON.parse(document.getElementById('bh-model-state').dataset.state);return values;}catch{return {};}}
  const values=Object.fromEntries(controls[lab].map(id=>{const el=document.getElementById(id);return[id,el.type==='checkbox'?el.checked:el.value]}));
  for(const mode of modes[lab]||[]){const el=document.querySelector(`[data-${mode}][aria-pressed="true"]`);if(el)values['mode:'+mode]=el.dataset[mode];}return values;
 }
 function draw(){panel.querySelector('#guide-results').innerHTML=Object.keys(captures).length?`<div class="guide-table"><table><caption>Valeurs relevées · ${esc(g.title)}</caption><thead><tr><th>Mesure</th><th>A</th><th>B</th></tr></thead><tbody>${Object.values(g.metrics).map(label=>`<tr><th scope="row">${esc(label)}</th><td>${esc(captures.A?.results[label]??'—')}</td><td>${esc(captures.B?.results[label]??'—')}</td></tr>`).join('')}</tbody></table></div>`:'<p>Aucun relevé. Manipulez le modèle puis relevez A et B.</p>';}
 function record(){return {laboratory:lab,guide:g.id,modelVersion:1,title:g.title,question:g.question,prediction:panel.querySelector('#guide-prediction').value,explanation:panel.querySelector('#guide-explanation').value,settings:settings(),captures,limit:g.limit,createdAt,updatedAt:new Date().toISOString()};}
 function save(){clearTimeout(timer);const value=record();try{AtlasNotebook.update(state=>({...state,labs:[...state.labs,lab],experiences:{...state.experiences,[key]:value}}));status('Expérience enregistrée dans votre carnet sur cet appareil.');return value;}catch{status('Stockage indisponible : exportez cette expérience avant de quitter la page.');return value;}}
 function queue(){if(restoring)return;clearTimeout(timer);timer=setTimeout(save,180);}
 function pause(){const play=document.getElementById(lab==='navier-stokes'?'run-toggle':lab==='antimatiere'?'collision-pause':'play');if(play&&!play.disabled&&(/pause/i.test(play.textContent)||play.getAttribute('aria-pressed')==='true'&&lab==='navier-stokes'))play.click();}
 function apply(values){restoring=true;pause();if(lab==='trou-noir'){window.dispatchEvent(new CustomEvent('the42laws:restore-black-hole',{detail:values}));}else{
  for(const mode of modes[lab]||[]){const v=values['mode:'+mode];for(const button of document.querySelectorAll(`[data-${mode}]`))if(button.dataset[mode]===v)button.click();}
  for(const id of (lab==='navier-stokes'?['quality',...controls[lab].filter(id=>id!=='quality')]:controls[lab])){const el=document.getElementById(id),v=values[id];if(v===undefined)continue;if(el.type==='checkbox'){if(typeof v!=='boolean')continue;el.checked=v;}else{if(el.tagName==='SELECT'&&![...el.options].some(o=>o.value===String(v)))continue;el.value=String(v);}el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));}
 }restoring=false;}
 if(stored){captures=stored.captures;createdAt=stored.createdAt||createdAt;panel.querySelector('#guide-prediction').value=stored.prediction;panel.querySelector('#guide-explanation').value=stored.explanation;if(stored.modelVersion===1){apply(stored.settings);status('Expérience reprise. Réponses et relevés restaurés ; seuls les paramètres du modèle sont rejoués.');}else status('Ancienne version du modèle : réponses conservées, réglages non rejoués.');}
 draw();panel.addEventListener('input',queue);
 document.addEventListener('input',e=>{if(controls[lab]?.includes(e.target.id))queue();});document.addEventListener('change',e=>{if(controls[lab]?.includes(e.target.id))queue();});
 document.addEventListener('click',e=>{if(e.target.closest((modes[lab]||[]).map(mode=>`[data-${mode}]`).join(',')||'[data-no-mode]'))queue();});window.addEventListener('the42laws:black-hole-settings',queue);
 panel.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-guide-setup')){restoring=true;pause();if(g.reset)document.getElementById(g.reset)?.click();if(g.click)document.querySelector(g.click)?.click();apply(g.set);restoring=false;setTimeout(save,0);}
  if(b.hasAttribute('data-guide-resume')){clearTimeout(timer);let saved;try{saved=AtlasNotebook.read().experiences[key];}catch{}if(saved?.modelVersion===1){apply(saved.settings);status('Derniers réglages restaurés. Les relevés A/B restent inchangés.');}else status('Aucun réglage compatible enregistré.');}
  if(b.dataset.guideCapture){const slot=b.dataset.guideCapture;captures[slot]={time:new Date().toISOString(),settings:settings(),results:Object.fromEntries(Object.entries(g.metrics).map(([id,label])=>[label,document.getElementById(id).innerText.trim()]))};draw();save();}
  if(b.hasAttribute('data-guide-save'))save();
  if(b.hasAttribute('data-guide-export')){const value=save(),state=AtlasCore.cleanState({experiences:{[key]:value},labs:[lab]});const url=URL.createObjectURL(new Blob([JSON.stringify({application:'The42laws',exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='the42laws-experience-'+lab+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Export prêt : ce fichier peut être importé dans le carnet.');}
 });
 function flush(){if(timer)save();}window.addEventListener('pagehide',flush);document.addEventListener('visibilitychange',()=>{if(document.hidden)flush();});
 if(new URLSearchParams(location.search).get('guide')===g.id&&location.hash==='#guide')panel.scrollIntoView();return true;
 }
 if(!mount()){const observer=new MutationObserver(()=>{if(mount())observer.disconnect();});observer.observe(document.getElementById('black-hole-root')||document.body,{childList:true,subtree:true});}
})();
