(function(){
 'use strict';
 const guides={
  photon:{id:'chemins',title:'Quand les franges disparaissent',question:19,predict:'Une information permettant de distinguer les chemins peut-elle changer les franges, même sans lecture humaine ?',change:'Appliquez le réglage initial, ajoutez 500 impacts avec « + 100 impacts » cinq fois et relevez A. Cochez « Information de chemin accessible », recommencez les impacts et relevez B.',observe:'Comparez la forme de la courbe théorique et celle des impacts, pas seulement leur nombre.',explain:'Expliquez pourquoi une somme de probabilités diffère du carré d’une somme d’amplitudes.',limit:'Ce tirage simule une distribution. Il ne sélectionne aucune interprétation de la mesure et ne représente pas un observateur conscient.',answer:'Quand les chemins sont distinguables, le terme d’interférence est absent dans ce modèle. Avec peu de points, les fluctuations peuvent masquer la forme attendue. La décohérence et le problème du résultat unique sont deux questions distinctes.',set:{wavelength:550,separation:180,'which-path':false},click:'[data-slits="2"]',reset:'reset',metrics:{count:'Impacts',energy:'Énergie',fringe:'Interfrange'}},
  temps:{id:'entropie',title:'La préparation change l’histoire',question:25,predict:'Avec les mêmes règles, partir d’un état équilibré donne-t-il la même évolution que partir avec tous les objets à gauche ?',change:'Appliquez le départ à gauche et faites 50 transitions ; relevez A. Choisissez ensuite « Moitié de chaque côté », faites 50 transitions et relevez B.',observe:'Observez la courbe entière : l’entropie peut baisser sur certaines transitions.',explain:'Expliquez le rôle du nombre de configurations et ce que le modèle ne dit pas sur le choix de l’état initial.',limit:'Aucune gravitation ni expansion dans ces urnes. Rejouer l’historique ne remonte pas le temps cosmologique.',answer:'Les mêmes transitions favorisent statistiquement les macroétats les plus nombreux, mais le départ détermine la trajectoire initiale. À l’équilibre, le système continue de fluctuer ; l’entropie n’augmente pas à chaque pas.',set:{'object-count':'40',initial:'left'},reset:'reset',metrics:{'left-count':'Objets à gauche',entropy:'S / k_B',multiplicity:'Configurations','history-value':'Transitions'}},
  neutrino:{id:'oscillations',title:'Doubler la distance et l’énergie',question:15,predict:'Que deviennent les probabilités si l’on double à la fois la distance et l’énergie ?',change:'Appliquez 500 km et 1 GeV ; relevez A. Passez à 1 000 km et 2 GeV, puis relevez B.',observe:'Comparez les trois probabilités, et vérifiez que leur somme est proche de 100 %. Les arrondis peuvent masquer une petite différence.',explain:'Reliez les résultats au rapport L/E, puis dites pourquoi une saveur ne se transforme pas selon un cycle obligatoire.',limit:'Oscillations dans le vide avec paramètres fixés ; pas d’effet de matière terrestre, de détecteur ni de flux solaire.',answer:'Dans ce modèle de propagation dans le vide, les phases relatives dépendent de L/E. Le même rapport redonne les mêmes probabilités. Il s’agit de probabilités de détection, pas d’une suite imposée électronique → muonique → tauique.',set:{energy:1,distance:500},click:'[data-flavor="1"]',metrics:{'prob-0':'Électronique','prob-1':'Muonique','prob-2':'Tauique'}},
  antimatiere:{id:'energie',title:'Où va l’énergie de la paire ?',question:25,predict:'Au repos, une annihilation libère-t-elle une énergie nulle ? Et si chaque particule reçoit 0,5 MeV d’énergie cinétique ?',change:'Appliquez le repos et relevez A. Réglez ensuite 0,5 MeV par particule et relevez B. Lancez les annihilations pour regarder le schéma.',observe:'Comparez l’énergie totale et l’énergie par photon, en faisant attention aux unités MeV et keV.',explain:'Additionnez les deux énergies de masse et les deux énergies cinétiques. Expliquez pourquoi cette conservation ne crée pas un excès initial de matière.',limit:'Canal à deux photons dans le référentiel du centre de masse, pas tous les canaux possibles ni une simulation de baryogenèse.',answer:'Au repos, la paire possède déjà environ 1,022 MeV d’énergie de masse : environ 511 keV pour chacun des deux photons. Ajouter 0,5 MeV à chaque particule porte le total à environ 2,022 MeV.',set:{kinetic:0},reset:'reset',metrics:{'total-energy':'Énergie totale','photon-energy':'Par photon',wavelength:'Longueur d’onde'}},
  'navier-stokes':{id:'dissipation',title:'Une référence pour tester le fluide',question:23,predict:'Sans force ni effet visuel de confinement, l’énergie de Taylor-Green reste-t-elle constante lorsque la viscosité est positive ?',change:'Appliquez Taylor-Green et relevez A à t = 0. Appuyez cinq fois sur « +10 pas », puis relevez B. Gardez la viscosité initiale et n’agissez pas sur le canevas.',observe:'Comparez l’énergie calculée, la référence théorique et l’écart numérique. Le calcul 2D et la grille finie ont leurs limites.',explain:'Distinguez dissipation visqueuse, erreur numérique et force extérieure. Pourquoi une animation ne prouve-t-elle pas une singularité 3D ?',limit:'Domaine 2D périodique. Le confinement ajoute une force visuelle ; le masque d’obstacle n’est pas un solveur rigoureux de paroi incompressible. Le schéma d’explosion reste illustratif.',answer:'La référence décroît comme exp(−4νt) pour l’énergie. Le schéma numérique peut dissiper davantage ; une concordance approchée est un contrôle utile, pas une démonstration du problème du millénaire.',set:{confinement:0},click:'[data-preset="taylor-green"]',metrics:{'stat-time':'Temps','stat-energy':'Énergie','stat-theory':'Référence','stat-gap':'Écart'}}
 };
 const lab=location.pathname.split('/').filter(Boolean)[0],g=guides[lab];if(!g)return;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const panel=document.createElement('section');panel.className='guided-experience';panel.id='guide';panel.setAttribute('aria-label','Expérience guidée');
 panel.innerHTML=`<span class="guide-kicker">EXPÉRIENCE GUIDÉE · 10 MIN ENVIRON</span><h2>${esc(g.title)}</h2><ol><li><h3>1. Faites une prédiction</h3><label for="guide-prediction">${esc(g.predict)}</label><textarea id="guide-prediction" maxlength="3000" placeholder="Je pense que… parce que…"></textarea></li><li><h3>2. Changez un paramètre</h3><p>${esc(g.change)}</p><button type="button" data-guide-setup>Appliquer le réglage initial</button><a href="#${lab==='photon'||lab==='temps'?'experience':'laboratoire'}">Aller aux commandes ↓</a><p class="guide-small">Ce bouton remet les réglages du modèle au point de départ.</p></li><li><h3>3. Observez et comparez</h3><p>${esc(g.observe)}</p><div class="guide-actions"><button type="button" data-guide-capture="A">Relever A</button><button type="button" data-guide-capture="B">Relever B</button></div><div id="guide-results"><p>Aucun relevé. Utilisez les commandes du laboratoire, puis relevez le résultat affiché.</p></div></li><li><h3>4. Expliquez le résultat</h3><label for="guide-explanation">${esc(g.explain)}</label><textarea id="guide-explanation" maxlength="3000" placeholder="J’observe que… Ce modèle permet de dire…"></textarea><details><summary>Comparer avec une piste d’explication</summary><p>${esc(g.answer)}</p></details></li></ol><p class="guide-limit"><strong>Limite du modèle.</strong> ${esc(g.limit)}</p><div class="guide-actions"><button type="button" data-guide-export>Exporter mes observations</button><a href="../dossiers/${g.question}/">Poursuivre avec le dossier ${g.question} →</a><a href="?guide=${g.id}#guide">Lien permanent de cette expérience</a></div><p class="guide-small">Réponses temporaires, conservées seulement dans cette page. Exportez-les avant de la quitter. Le lien partage le guide, sans vos réponses ni les tirages aléatoires.</p><p id="guide-status" role="status"></p>`;
 const anchor=document.getElementById('experience')||document.getElementById('laboratoire');anchor.before(panel);
 const captures={};const status=msg=>document.getElementById('guide-status').textContent=msg;
 function setup(){
  const play=document.getElementById(lab==='navier-stokes'?'run-toggle':lab==='antimatiere'?'collision-pause':'play');
  if(play&&!play.disabled&&((play.getAttribute('aria-pressed')==='true'&&lab==='navier-stokes')||/Pause/.test(play.textContent)&&play.getAttribute('aria-pressed')!=='true'))play.click();
  if(g.reset)document.getElementById(g.reset).click();
  if(g.click)document.querySelector(g.click).click();
  for(const [id,v]of Object.entries(g.set)){const input=document.getElementById(id);if(input.type==='checkbox')input.checked=v;else input.value=String(v);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}
  status('Réglage initial appliqué. Faites votre expérience puis relevez A et B.');
 }
 panel.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-guide-setup'))setup();
  if(b.dataset.guideCapture){const slot=b.dataset.guideCapture;captures[slot]={time:new Date().toISOString(),settings:Object.fromEntries(Object.keys(g.set).map(id=>{const el=document.getElementById(id);return[id,el.type==='checkbox'?el.checked:el.value]})),results:Object.fromEntries(Object.entries(g.metrics).map(([id,label])=>[label,document.getElementById(id).textContent.trim()]))};
   document.getElementById('guide-results').innerHTML=`<div class="guide-table"><table><caption>Relevés des valeurs affichées · ${esc(g.title)}</caption><thead><tr><th>Mesure</th><th>A</th><th>B</th></tr></thead><tbody>${Object.values(g.metrics).map(label=>`<tr><th scope="row">${esc(label)}</th><td>${esc(captures.A?.results[label]||'—')}</td><td>${esc(captures.B?.results[label]||'—')}</td></tr>`).join('')}</tbody></table></div>`;status('Relevé '+slot+' enregistré dans cette page.');
  }
  if(b.hasAttribute('data-guide-export')){const data={application:'The42laws',laboratory:lab,guide:g.id,prediction:document.getElementById('guide-prediction').value,explanation:document.getElementById('guide-explanation').value,captures,limit:g.limit};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='the42laws-experience-'+lab+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Export des observations préparé.');}
 });
 if(new URLSearchParams(location.search).get('guide')===g.id&&location.hash==='#guide')panel.scrollIntoView();
})();
