(function(root){
 'use strict';
 const C=typeof module==='object'&&module.exports?require('./core.js'):root.AtlasCore;
 function create(D,state=C.cleanState({})){
 const E=C.escape,qBy=id=>D.questions.find(q=>q.id===Number(id));
 const badge=q=>`<span class="badge ${q.researched?'ready':''}">${E(q.status)}</span>`;
 const link=(href,text,primary=false)=>`<a class="button ${primary?'primary':''}" href="${E(C.canonicalHref(href))}">${text} <span aria-hidden="true">↗</span></a>`;
 const notFound=()=>'<div class="page"><h1>Page introuvable</h1></div>';
function constellation(){
let nodes='',lines='';
D.domains.forEach((d,g)=>{
 const angle=(g/7)*Math.PI*2-Math.PI/2,cx=210+125*Math.cos(angle),cy=210+125*Math.sin(angle),count=d.range[1]-d.range[0]+1;
 lines+=`<line x1="210" y1="210" x2="${cx}" y2="${cy}" stroke="${d.color}" opacity=".18"/>`;
 for(let k=0;k<count;k++){const a=k/count*Math.PI*2,x=cx+34*Math.cos(a),y=cy+34*Math.sin(a),q=qBy(d.range[0]+k);lines+=`<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="${d.color}" opacity=".24"/>`;nodes+=`<a href="#/question/${q.id}" aria-label="Question ${q.id} : ${E(q.title)}"><title>${E(q.title)}</title><circle cx="${x}" cy="${y}" r="5" fill="${d.color}"/><circle cx="${x}" cy="${y}" r="11" fill="transparent"/></a>`;}
 nodes+=`<a href="#/atlas?d=${d.id}" aria-label="Explorer ${E(d.name)}"><text x="${cx}" y="${cy+4}" text-anchor="middle" fill="${d.color}" font-size="11" font-family="Georgia">${d.roman}</text></a>`;
});
return `<div class="constellation"><svg viewBox="0 0 420 420" role="group" aria-label="Carte des 42 questions, regroupées en sept domaines"><circle cx="210" cy="210" r="170" fill="none" stroke="#30362d" stroke-dasharray="2 8"/><circle cx="210" cy="210" r="125" fill="none" stroke="#30362d"/><circle cx="210" cy="210" r="68" fill="none" stroke="#30362d"/>${lines}<text x="210" y="220" text-anchor="middle" fill="#edf0e7" font-size="46" font-family="Georgia">42</text><text x="210" y="240" text-anchor="middle" fill="#a0aa99" font-size="7" letter-spacing="2">QUESTIONS OUVERTES</text>${nodes}</svg><div class="constellation-caption"><span>CARTE DES QUESTIONS</span><span>CHAQUE POINT EST UNE ENTRÉE ↗</span></div></div>`;
}
function labCard(l){return `<a class="lab-card" href="${l.url}" style="--accent:${l.color}" data-lab="${l.id}"><div class="lab-art" aria-hidden="true"><img src="/atlas/brand-lab-${l.id}.svg" width="600" height="430" loading="lazy" alt=""><span class="lab-index">${l.number} /</span><span class="lab-glyph">${l.symbol}</span></div><div class="lab-caption"><span class="eyebrow">LABORATOIRE / MODÈLE PÉDAGOGIQUE</span><h3>${l.title}</h3><p>${l.subtitle}</p><span class="arrow" aria-hidden="true">↗</span></div></a>`;}
function pathCards(){return `<div class="path-grid">${D.paths.map(p=>`<a class="path-card" href="#/parcours/${p.id}" style="--accent:${p.color}"><span class="path-symbol" aria-hidden="true">${p.symbol}</span><span class="eyebrow">${p.eyebrow}</span><h3>${p.title}</h3><p>${p.description}</p><small>${p.steps.length} ÉTAPES À EXPLORER →</small></a>`).join('')}</div>`;}
function home(){return `<div class="page brand-home">${state.last?`<a class="resume" href="#/question/${state.last}">Reprendre l’exploration <b>Question ${state.last} · ${E(qBy(state.last).title)} →</b></a>`:''}
<section class="horizon-hero" aria-labelledby="horizon-title"><div class="horizon-visual" aria-hidden="true"><img class="horizon-poster" src="/atlas/brand-lab-trou-noir.svg" width="600" height="430" alt="" fetchpriority="high"></div><div id="horizon-scene" class="horizon-scene"></div><div class="horizon-shade" aria-hidden="true"></div><div class="horizon-top"><span class="eyebrow">THE42LAWS / UN ATLAS DU RÉEL</span><span class="horizon-edition">L’EXPLORATION COMMENCE ICI</span></div><div class="horizon-copy"><span class="horizon-overline"><i aria-hidden="true"></i> 42 QUESTIONS. UN MONDE À EXPLORER.</span><h1 id="horizon-title">Le réel dépasse<br><em>notre imagination.</em></h1><p>De l’infiniment petit aux frontières de l’Univers,<br class="desktop-break"> explorez ce que l’on sait.<br>Et tout ce qu’il reste à comprendre.</p><div class="actions">${link('#/atlas','Explorer les 42 questions',true)}${link('#/parcours','Par où commencer ?')}</div></div><div class="horizon-bottom"><span>OBSERVER. QUESTIONNER. COMPRENDRE.</span><a href="/trou-noir/"><span class="horizon-orbit" aria-hidden="true">◌</span><span>AUX FRONTIÈRES DU VISIBLE<small>Explorer le trou noir ↗</small></span></a></div></section>
<div class="stats-row"><div class="stat"><strong>42</strong><span>questions<br>pour interroger le réel</span></div><div class="stat"><strong>07</strong><span>domaines<br>qui se répondent</span></div><div class="stat"><strong>${String(D.labs.length).padStart(2,'0')}</strong><span>laboratoires<br>pour expérimenter</span></div><div class="stat"><strong>${String(D.questions.filter(q=>q.researched).length).padStart(2,'0')}</strong><span>synthèses provisoires<br>à approfondir</span></div></div>
<section class="brand-labs"><div class="section-head"><div><span class="eyebrow">01 / COMPRENDRE EN EXPLORANT</span><h2>Le réel, à l’épreuve<br><em>de votre curiosité.</em></h2></div><a href="#/laboratoires">Tous les laboratoires ↗</a></div><div class="lab-grid">${D.labs.map(labCard).join('')}</div></section>
<section class="brand-map"><div class="map-copy"><span class="eyebrow">02 / UNE CARTE POUR S’ORIENTER</span><h2>Tout commence<br>par <em>une question.</em></h2><p>De l’existence à la conscience, choisissez un domaine ou entrez par un point de la carte. Les liens sont des pistes d’exploration, pas des réponses déjà acquises.</p><div class="domain-keys">${D.domains.map(d=>`<a href="#/atlas?d=${d.id}" style="--accent:${d.color}"><span>${d.roman}</span>${E(d.name)}<i aria-hidden="true">↗</i></a>`).join('')}</div></div>${constellation()}</section>
<section class="brand-research"><div class="section-head"><div><span class="eyebrow">03 / LES DOSSIERS DE RECHERCHE</span><h2>Prendre le temps<br><em>d’approfondir.</em></h2></div><a href="#/atlas?etat=ready">Les synthèses ↗</a></div><div class="research-grid">${D.questions.filter(q=>q.researched).map(q=>`<a class="research-card" href="#/question/${q.id}" style="--accent:${q.color}"><span class="research-number" aria-hidden="true">${String(q.id).padStart(2,'0')}</span><span class="eyebrow">${E(q.domainName)}</span><h3>${E(q.title)}</h3>${badge(q)}<small>L’essentiel · Dossier · ${q.sourceCount} références ↗</small></a>`).join('')}</div><div class="section-tools">${link('#/particules','Tableau des particules')}${link('#/liens','Carte des liens')}${link('#/apropos','Découvrir le projet')}</div></section>
<section><div class="section-head"><div><span class="eyebrow">04 / SUIVRE UN FIL</span><h2>Une question en appelle <em>une autre.</em></h2></div></div>${pathCards()}</section>
<section class="brand-closing"><img src="/atlas/favicon-42-180.png" width="60" height="60" loading="lazy" alt=""><div><span class="eyebrow">UN CARNET OUVERT SUR LE MONDE</span><h2>Rester curieux.</h2><p>Une intuition, une objection, une idée à poursuivre.<br>Votre exploration mérite d’être gardée.</p></div>${link('#/carnet','Ouvrir mon carnet')}</section></div>`;}
function laboratories(){return `<div class="page"><div class="page-intro"><span class="eyebrow">MANIPULER POUR COMPRENDRE</span><h1>Le laboratoire du réel.</h1><p>${D.labs.length} explorations interactives pour passer d’une idée à une expérience. Chaque laboratoire expose ses hypothèses, les limites de son modèle et ses sources.</p></div><div class="lab-grid">${D.labs.map(labCard).join('')}</div><div class="notice" style="margin-top:30px">Les portraits sont des évocations artistiques. Les calculs et les modèles pédagogiques sont expliqués dans chaque laboratoire.</div><div class="section-head"><h2>Relier les expériences</h2></div>${pathCards()}</div>`;}
function paths(id){const p=D.paths.find(x=>x.id===id);if(id&&!p)return notFound();if(!p)return `<div class="page gateway-page"><section class="gateway-hero" aria-labelledby="gateway-title"><div id="gateway-flow-root" class="gateway-effect"></div><div class="gateway-card"><img src="/atlas/favicon-42-48.png" width="42" height="42" alt=""><span class="eyebrow">APPRENDRE EN SUIVANT UN FIL</span><h1 id="gateway-title">Choisissez votre<br><em>point de départ.</em></h1><p>De la matière à la conscience,<br>laissez une question vous conduire à la suivante.</p>${link('#/parcours/matiere','Commencer par la matière',true)}<small>${D.paths.length} parcours · À votre rythme · Sans compte</small></div><span class="gateway-corner" aria-hidden="true">DES QUESTIONS / DES CHEMINS</span></section><div class="section-head"><div><span class="eyebrow">CHOISIR UN ITINÉRAIRE</span><h2>Suivez <em>votre curiosité.</em></h2></div></div>${pathCards()}<p class="gateway-reading-note">Toutes les étapes de lecture disposent d’une synthèse provisoire. Ouvrir un laboratoire ou marquer un dossier lu ne signifie pas avoir validé sa compréhension.</p></div>`;return `<div class="page"><div class="page-intro"><a class="eyebrow" href="#/parcours">← LES PARCOURS</a><h1>${p.title}</h1><p>${p.description}</p></div>${p.steps.map((s,i)=>{const item=s.type==='lab'?D.labs.find(l=>l.id===s.id):qBy(s.id),done=s.type==='lab'?state.labs.includes(s.id):state.read.includes(s.id);return `<article class="step" style="--accent:${p.color}"><span>${String(i+1).padStart(2,'0')}</span><div><span class="eyebrow">${s.type==='lab'?'LABORATOIRE INTERACTIF':`QUESTION ${item.id}`}${done?' · '+(s.type==='lab'?'DÉJÀ OUVERT':'MARQUÉ LU'):''}</span><h2>${E(item.title)}</h2>${s.type==='lab'?`<p>${item.description}</p>`:badge(item)}</div><a class="button" href="${s.type==='lab'?item.url:'#/question/'+item.id}" ${s.type==='lab'?`data-lab="${item.id}"`:''}>${s.type==='lab'?'Expérimenter':'Explorer'} ↗</a></article>`;}).join('')}${p.further?.length?`<div class="notice">Pour prolonger, hors parcours : ${p.further.map(id=>`<a href="/dossiers/${id}/">Question ${id} — à explorer</a>`).join(' · ')}</div>`:''}</div>`;}
 function rows(items){return items.map(q=>`<a class="question-row" href="/dossiers/${q.id}/"><span class="question-number">${String(q.id).padStart(2,'0')}</span><h3>${E(q.title)}</h3>${badge(q)}</a>`).join('');}
 function domain(id){const d=D.domains.find(d=>d.id===id);if(!d)return notFound();const items=D.questions.filter(q=>q.domain===id),ready=items.filter(q=>q.researched);return `<div class="page"><nav class="seo-breadcrumbs" aria-label="Fil d’Ariane"><a href="/">Accueil</a><a href="/dossiers/">Les 42 questions</a><span>${E(d.name)}</span></nav><div class="page-intro"><span class="eyebrow">DOMAINE ${d.roman} / THE42LAWS</span><h1>${E(d.name)} : ${E(d.subtitle)}</h1><p>${E(d.description)} ${items.length} questions, ${ready.length} synthèse${ready.length>1?'s':''} provisoire${ready.length>1?'s':''}.</p></div><div class="notice">Les synthèses distinguent observations, modèles et hypothèses. Les dossiers à explorer restent sans réponse publiée.</div><h2>Les synthèses disponibles</h2>${ready.length?rows(ready):'<p>Aucune synthèse publiée dans ce domaine pour le moment.</p>'}<h2>Toutes les questions de ce domaine</h2>${rows(items)}<div class="actions">${link('/methode/','Notre méthode')}${link('/sources/','Les références')}${link('/parcours/','Suivre un parcours')}</div></div>`;}
 function atlas(){return `<div class="page"><div class="page-intro"><h1>Les 42 questions.</h1><p>Sept domaines pour explorer le réel. Les synthèses sont provisoires ; les autres questions restent à explorer.</p></div>${D.domains.map(d=>`<section class="question-group"><h2><a href="/domaines/${d.id}/">${E(d.name)} — ${E(d.subtitle)}</a></h2><p>${E(d.description)}</p>${rows(D.questions.filter(q=>q.domain===d.id))}</section>`).join('')}</div>`;}
 function documentPage(kind){const doc=kind==='methode'?D.method:D.sources,title=kind==='methode'?'Notre méthode':'Registre des sources';return `<div class="page"><div class="page-intro"><h1>${title}</h1><p>${kind==='methode'?'Distinguer ce qui est observé, démontré, proposé ou encore inconnu.':'Un registre de travail : dates et niveaux de consultation précisent l’état documentaire des références.'}</p>${link(kind==='methode'?'/sources/':'/methode/',kind==='methode'?'Consulter les sources':'Comprendre la méthode')}</div><article class="prose">${doc.html}</article></div>`;}
 function glossary(){return `<div class="page"><div class="page-intro"><h1>Le glossaire.</h1><p>Des définitions pédagogiques pour accompagner les dossiers et comprendre leurs modèles.</p></div><div class="glossary-grid">${D.glossary.map(t=>`<article class="definition-card" id="${E(t.id)}"><h2>${E(t.term)}</h2><p>${E(t.definition)}</p><small>POUR APPROFONDIR : ${t.questions.map(id=>`<a href="/dossiers/${id}/">Question ${id}</a>`).join(' · ')}</small></article>`).join('')}</div><p>Ces repères ne remplacent pas les définitions propres à chaque modèle. <a href="/methode/">Consulter notre méthode</a>.</p></div>`;}
 function frame(eyebrow,title,intro,body){return `<div class="page"><div class="page-intro"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${intro}</p></div>${body}</div>`;}
function about(){return frame('OBSERVER. QUESTIONNER. COMPRENDRE.','Un atlas en construction.','The42laws rassemble 42 questions sur le réel. Le nom désigne un programme de recherche, pas 42 lois démontrées.',`<div class="about-grid"><article><span class="eyebrow">LIRE ET EXPÉRIMENTER</span><h2>Des connaissances révisables.</h2><p>${D.questions.filter(q=>q.researched).length} dossiers portent aujourd’hui le statut « Synthèse provisoire ». Les autres restent ouverts à la recherche. Chaque modèle expose ses hypothèses et ses limites.</p><a class="button" href="#/methode">Notre méthode ↗</a></article><article><span class="eyebrow">VOTRE CARNET</span><h2>Vos notes vous appartiennent.</h2><p>Les notes et favoris sont conservés dans le navigateur. Aucun compte, synchronisation ou envoi des notes à un serveur. Un export permet d’en conserver une copie et un import permet de la fusionner sur un autre navigateur.</p><a class="button" href="#/carnet">Ouvrir mon carnet ↗</a></article><article><span class="eyebrow">PARTAGER UNE LECTURE</span><h2>Un lien vers chaque question.</h2><p>Le bouton de partage copie l’adresse du dossier, sans les notes personnelles. Sur la version locale, ce lien fonctionne sur l’appareil qui héberge l’atlas. Le site public est disponible sur the42laws.fr ; chaque dossier possède une adresse permanente.</p><a class="button" href="#/atlas">Explorer les dossiers ↗</a></article><article><span class="eyebrow">ACCESSIBILITÉ</span><h2>Plusieurs façons d’explorer.</h2><p>Navigation au clavier, définitions en fenêtre accessible, commandes explicites et tableaux défilables. Les expériences démarrent à votre demande ; compteurs, équations et textes accompagnent les représentations graphiques.</p><a class="button" href="#/glossaire">Parcourir le glossaire ↗</a></article></div><div class="notice">Les dossiers 23 et 41 conservent leurs recherches originales et leurs réserves. Les vues courtes précisent la portée des conclusions. La présence d’une référence ne signifie pas une lecture intégrale : son mode de consultation est indiqué.</div>`);}
 function particles(){return frame('COMPRENDRE LE MODÈLE STANDARD','Les familles du réel.','17 entrées pédagogiques pour comparer les propriétés des particules élémentaires.',`<div class="glossary-grid">${D.particles.map(p=>`<article class="definition-card"><h2>${E(p.name)} (${E(p.symbol)})</h2><p>${E(p.role)}</p><dl><dt>Charge électrique</dt><dd>${E(p.charge)}</dd><dt>Spin</dt><dd>${E(p.spin)}</dd><dt>Masse</dt><dd>${E(p.mass)}</dd></dl><p><a href="${E(p.source)}" target="_blank" rel="noopener noreferrer">Référence de la fiche</a></p>${rows(p.questions.map(qBy))}</article>`).join('')}</div><p>W⁺ et W⁻ partagent une case, les huit gluons aussi. Les antiparticules des fermions ne sont pas affichées séparément. Le graviton hypothétique ne figure pas parmi les particules établies.</p>`);}
 function connections(){return frame('UNE QUESTION EN APPELLE UNE AUTRE','La carte des liens.','Des connexions éditoriales pour poursuivre la lecture. Elles ne constituent pas une démonstration entre les sujets.',D.connections.map(e=>`<article class="connection-detail"><h2>${E(e.label)}</h2><a href="/dossiers/${e.from}/">${E(qBy(e.from).title)}</a><p>↔ <a href="/dossiers/${e.to}/">${E(qBy(e.to).title)}</a></p></article>`).join(''));}
 function page(parts){return parts[0]==='accueil'?home():parts[0]==='atlas'?atlas():parts[0]==='domaine'?domain(parts[1]):parts[0]==='parcours'?paths(parts[1]):parts[0]==='laboratoires'?laboratories():parts[0]==='glossaire'?glossary():parts[0]==='particules'?particles():parts[0]==='liens'?connections():parts[0]==='apropos'?about():documentPage(parts[0]);}
 function normalize(html){return html.replace(/href="([^"]+)"/g,(_,href)=>`href="${C.canonicalHref(href.replaceAll('&amp;','&')).replaceAll('&','&amp;')}"`);}
 return {home:()=>normalize(home()),labCard:l=>normalize(labCard(l)),pathCards:()=>normalize(pathCards()),paths:id=>normalize(paths(id)),laboratories:()=>normalize(laboratories()),domain,atlas,page:parts=>normalize(page(parts))};
 }
 const api={create};if(typeof module==='object'&&module.exports)module.exports=api;else root.AtlasPublicViews=api;
})(globalThis);
